// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "rectangle.h"
#pragma warning(disable: 4100)

const reflect::meta_t& reflect::Type<math::rect>::meta()
{
    static reflect::meta_t s_meta {
        { "forward_declaration", "namespace math { typedef struct rectangle_t<float> rect; }" },
    };
    return s_meta;
}
const char* const reflect::Type<math::rect>::name() { return "math::rect"; }

const reflect::properties_t& Type<math::rect>::properties()
{
    static reflect::properties_t s_properties {
        { "x", reflect::Property{ offsetof(math::rect, x), reflect::meta_t { }, "x", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
        { "y", reflect::Property{ offsetof(math::rect, y), reflect::meta_t { }, "y", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
        { "width", reflect::Property{ offsetof(math::rect, width), reflect::meta_t { }, "width", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
        { "height", reflect::Property{ offsetof(math::rect, height), reflect::meta_t { }, "height", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
    };
    return s_properties;
}

std::size_t reflect::Type<math::rect>::size()
{
    return sizeof(math::rect);
}

void reflect::Type<math::rect>::from_string(const std::string& str, math::rect& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    stream >> type.x;
    stream >> type.y;
    stream >> type.width;
    stream >> type.height;
}

std::string reflect::Type<math::rect>::to_string(const math::rect& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    stream << type.x;
    stream << type.y;
    stream << type.width;
    stream << type.height;
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<math::rect>::from_json(const std::string& json, math::rect& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            if (key == "x") reflect::encoding::json::Deserializer::parse(value, type.x);
            if (key == "y") reflect::encoding::json::Deserializer::parse(value, type.y);
            if (key == "width") reflect::encoding::json::Deserializer::parse(value, type.width);
            if (key == "height") reflect::encoding::json::Deserializer::parse(value, type.height);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<math::rect>::to_json(const math::rect& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"math::rect\"" << "," << std::endl;
    stream << offset << "    " << "\"x\": " << reflect::encoding::json::Serializer::to_string(type.x) << "," << std::endl;
    stream << offset << "    " << "\"y\": " << reflect::encoding::json::Serializer::to_string(type.y) << "," << std::endl;
    stream << offset << "    " << "\"width\": " << reflect::encoding::json::Serializer::to_string(type.width) << "," << std::endl;
    stream << offset << "    " << "\"height\": " << reflect::encoding::json::Serializer::to_string(type.height) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}