// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

namespace math
{
    class transform;
}

template <>
struct reflect::Type<class math::transform>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, math::transform& type);
    static std::string to_string(const math::transform& type);
    static void from_json(const std::string& json, math::transform& type);
    static std::string to_json(const math::transform& type, const std::string& offset = "");
};