// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct ComponentType
{
    ComponentType();

    static const meta_t& meta();
    static const char* name();
    static class Component* const instantiate();
};
extern ComponentType __component_type;

