// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "image_asset.h"

const meta_t& ImageAsset::getTypeMeta() const { return __ImageAssetType::type().meta; }
const std::string& ImageAsset::getTypeName() const { return __ImageAssetType::type().name; }
const properties_t ImageAsset::getTypeProperties() const {
    properties_t properties = Asset::getTypeProperties();
    return properties;
}
std::size_t ImageAsset::getTypeSize() const { return __ImageAssetType::type().size; }
const meta_t& ImageAsset::staticTypeMeta() { return __ImageAssetType::type().meta; }
const std::string& ImageAsset::staticTypeName() { return __ImageAssetType::type().name; }

const TypeDefinition& __ImageAssetType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new ImageAsset(); }, "ImageAsset", {
        std::make_pair("CreateInEditor", "false"),
        std::make_pair("Extension", ".png|.jpg|.jpeg|.bmp"),
        std::make_pair("Type", "Asset"),
    }, sizeof(ImageAsset));
    return s_typeDefinition;
}
