// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "prefab_asset_handler.h"

const reflect::meta_t& reflect::Type<PrefabAssetHandler>::meta()
{
    static reflect::meta_t s_meta {
        { "Type", "AssetHandler" },
    };
    return s_meta;
}
const char* const reflect::Type<PrefabAssetHandler>::name() { return "PrefabAssetHandler"; }

const reflect::properties_t& Type<PrefabAssetHandler>::properties()
{
    static reflect::properties_t s_properties {
        // Parent class AssetHandler properties
        // Properties
    };
    return s_properties;
}

std::size_t reflect::Type<PrefabAssetHandler>::size()
{
    return sizeof(PrefabAssetHandler);
}

void reflect::Type<PrefabAssetHandler>::from_string(const std::string& str, PrefabAssetHandler& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    // Parent class AssetHandler properties
    // Properties
}

std::string reflect::Type<PrefabAssetHandler>::to_string(const PrefabAssetHandler& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    // Parent class AssetHandler properties
    // Properties
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<PrefabAssetHandler>::from_json(const std::string& json, PrefabAssetHandler& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            // Parent class AssetHandler properties
            // Properties
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<PrefabAssetHandler>::to_json(const PrefabAssetHandler& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"PrefabAssetHandler\"" << "," << std::endl;
    // Parent class AssetHandler properties
    // Properties
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& PrefabAssetHandler::type_meta() const { return reflect::Type<PrefabAssetHandler>::meta(); }
const char* const PrefabAssetHandler::type_name() const { return reflect::Type<PrefabAssetHandler>::name(); }
const reflect::properties_t& PrefabAssetHandler::type_properties() const { return reflect::Type<PrefabAssetHandler>::properties(); }
PrefabAssetHandler::operator std::string() const { return reflect::Type<PrefabAssetHandler>::to_string(*this); }
void PrefabAssetHandler::from_string(const std::string& str) { reflect::Type<PrefabAssetHandler>::from_string(str, *this); }
void PrefabAssetHandler::from_json(const std::string& json) { reflect::Type<PrefabAssetHandler>::from_json(json, *this); }
std::string PrefabAssetHandler::to_json(const std::string& offset) const { return reflect::Type<PrefabAssetHandler>::to_json(*this, offset); }