// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "editor_settings.h"
#pragma warning(disable: 4100)

IType* const reflect::Type<EditorSettings>::instantiate()
{
    return dynamic_cast<IType*>(new EditorSettings());
}

const reflect::meta_t& reflect::Type<EditorSettings>::meta()
{
    static reflect::meta_t s_meta {
    };
    return s_meta;
}
const char* const reflect::Type<EditorSettings>::name() { return "EditorSettings"; }

const reflect::properties_t& Type<EditorSettings>::properties()
{
    static reflect::properties_t s_properties {
        { "windowsVisibility", reflect::Property{ offsetof(EditorSettings, windowsVisibility), reflect::meta_t { }, "windowsVisibility", reflect::PropertyType{ "std::map<std::string, bool>", { 
            reflect::PropertyType{ "std::string", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(std::string), reflect::PropertyType::Type::T_string },
            reflect::PropertyType{ "bool", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(bool), reflect::PropertyType::Type::T_bool },
        }, reflect::PropertyType::DecoratorType::D_raw, sizeof(std::map<std::string, bool>), reflect::PropertyType::Type::T_template } } },
    };
    return s_properties;
}

std::size_t reflect::Type<EditorSettings>::size()
{
    return sizeof(EditorSettings);
}

void reflect::Type<EditorSettings>::from_string(const std::string& str, EditorSettings& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    {
        std::size_t size;
        stream >> size;
        for (int i = 0; i < size; ++i)
        {
            std::string key;
            stream >> key;
            bool value;
            stream >> value;
            type.windowsVisibility.insert(std::make_pair(key, value));
        }
    }
}

std::string reflect::Type<EditorSettings>::to_string(const EditorSettings& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    {
        stream << type.windowsVisibility.size();
        for (const auto& pair : type.windowsVisibility)
        {
            stream << pair.first;
            stream << pair.second;
        }
    }
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<EditorSettings>::from_json(const std::string& json, EditorSettings& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            if (key == "windowsVisibility") reflect::encoding::json::Deserializer::parse(value, type.windowsVisibility);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<EditorSettings>::to_json(const EditorSettings& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"EditorSettings\"" << "," << std::endl;
    stream << offset << "    " << "\"windowsVisibility\": " << reflect::encoding::json::Serializer::to_string(type.windowsVisibility) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& EditorSettings::type_meta() const { return reflect::Type<EditorSettings>::meta(); }
const char* const EditorSettings::type_name() const { return reflect::Type<EditorSettings>::name(); }
const reflect::properties_t& EditorSettings::type_properties() const { return reflect::Type<EditorSettings>::properties(); }
EditorSettings::operator std::string() const { return reflect::Type<EditorSettings>::to_string(*this); }
void EditorSettings::from_string(const std::string& str)
{
    reflect::Type<EditorSettings>::from_string(str, *this);
    type_initialize();
}
void EditorSettings::from_json(const std::string& json)
{
    reflect::Type<EditorSettings>::from_json(json, *this);
    type_initialize();
}
std::string EditorSettings::to_json(const std::string& offset) const { return reflect::Type<EditorSettings>::to_json(*this, offset); }