// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct MenuItemType
{
    MenuItemType();

    static const meta_t& meta();
    static const char* name();
    static class MenuItem* const instantiate();
};
extern MenuItemType __menuitem_type;

