// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct WindowType
{
    WindowType();

    static const meta_t& meta();
    static const char* name();
    static class Window* const instantiate();
};
extern WindowType __window_type;

