// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "rotating_shields_component.h"

const meta_t& RotatingShieldsComponent::getTypeMeta() const { return RotatingShieldsComponentType::type().meta; }
const std::string& RotatingShieldsComponent::getTypeName() const { return RotatingShieldsComponentType::type().name; }
const properties_t RotatingShieldsComponent::getTypeProperties() const {
    member_address_t origin = reinterpret_cast<member_address_t>(this);
    properties_t properties = WeaponComponent::getTypeProperties();
    properties.insert(std::make_pair<std::string, Property>("m_bulletPrefab", Property("m_bulletPrefab", Property::TypeDescriptor("PrefabAssetPtr", Property::Type::T_unknown, Property::DecoratorType::D_normalized, {}), sizeof(PrefabAssetPtr), origin + offsetof(RotatingShieldsComponent, m_bulletPrefab), {
    })));
    return properties;
}
std::size_t RotatingShieldsComponent::getTypeSize() const { return RotatingShieldsComponentType::type().size; }

const TypeDefinition& RotatingShieldsComponentType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new RotatingShieldsComponent(); }, "RotatingShieldsComponent", {
        std::make_pair("Category", "Component"),
    }, sizeof(RotatingShieldsComponent));
    return s_typeDefinition;
}
