// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "command_phase.h"

const char* EnumType<CommandPhase>::name() { return "CommandPhase"; }
const std::map<const char*, int>  EnumType<CommandPhase>::values()
{
    static std::map<const char*, int> s_values{
        { "Request", static_cast<int>(CommandPhase::Request) }, 
        { "Response", static_cast<int>(CommandPhase::Response) }, 
    };
    return s_values;
}

