// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

#include "command_phase_generated.h"

ENUM()
enum class CommandPhase : int
{
    Request = 0,
    Response = 1,
};