// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "net_mode.h"

const char* EnumType<NetMode>::name() { return "NetMode"; }
const std::map<const char*, int>  EnumType<NetMode>::values()
{
    static std::map<const char*, int> s_values{
        { "Client", static_cast<int>(NetMode::Client) }, 
        { "Shared", static_cast<int>(NetMode::Shared) }, 
        { "Server", static_cast<int>(NetMode::Server) }, 
    };
    return s_values;
}

