// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "ui_element.h"

const meta_t& UIElement::getTypeMeta() const { return UIElementType::type().meta; }
const std::string& UIElement::getTypeName() const { return UIElementType::type().name; }
const properties_t UIElement::getTypeProperties() const {
    properties_t properties = Entity::getTypeProperties();
    return properties;
}
std::size_t UIElement::getTypeSize() const { return UIElementType::type().size; }

const TypeDefinition& UIElementType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new UIElement(); }, "UIElement", {
        std::make_pair("Type", "Entity"),
    }, sizeof(UIElement));
    return s_typeDefinition;
}
