// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct AssetInspectorWindowType : RegisteredInTypeFactory<AssetInspectorWindowType>
{
    AssetInspectorWindowType();

    static const meta_t& meta();
    static const char* name();
    static class AssetInspectorWindow* const instantiate();
    static bool registered() { return value; };
};

