// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct ContentBrowserWindowType : RegisteredInTypeFactory<ContentBrowserWindowType>
{
    ContentBrowserWindowType() = delete;

    static const Type& type();
    static bool registered() { return value; };
};

