// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct EntityInspectorWindowType
{
    EntityInspectorWindowType();

    static const meta_t& meta();
    static const char* name();
    static class EntityInspectorWindow* const instantiate();
};
extern EntityInspectorWindowType __entityinspectorwindow_type;

