// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "entity_inspector_window.h"

const meta_t& EntityInspectorWindow::getTypeMeta() const { return EntityInspectorWindowType::type().meta; }
const std::string& EntityInspectorWindow::getTypeName() const { return EntityInspectorWindowType::type().name; }
const properties_t EntityInspectorWindow::getTypeProperties() const {
    member_address_t origin = reinterpret_cast<member_address_t>(this);
    properties_t properties = Window::getTypeProperties();
    return properties;
}
std::size_t EntityInspectorWindow::getTypeSize() const { return EntityInspectorWindowType::type().size; }

const Type& EntityInspectorWindowType::type()
{
    static const Type s_type([]() -> IType* { return new EntityInspectorWindow(); }, "EntityInspectorWindow", {
        std::make_pair("Category", "Window"),
    }, sizeof(EntityInspectorWindow));
    return s_type;
}
