// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "entity_inspector_window.h"

const reflect::meta_t& reflect::Type<EntityInspectorWindow>::meta()
{
    static reflect::meta_t s_meta {
        { "Type", "Window" },
    };
    return s_meta;
}
const char* const reflect::Type<EntityInspectorWindow>::name() { return "EntityInspectorWindow"; }

const reflect::properties_t& Type<EntityInspectorWindow>::properties()
{
    static reflect::properties_t s_properties {
        // Parent class Window properties
        // Properties
    };
    return s_properties;
}

std::size_t reflect::Type<EntityInspectorWindow>::size()
{
    return sizeof(EntityInspectorWindow);
}

void reflect::Type<EntityInspectorWindow>::from_string(const std::string& str, EntityInspectorWindow& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    // Parent class Window properties
    // Properties
}

std::string reflect::Type<EntityInspectorWindow>::to_string(const EntityInspectorWindow& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    // Parent class Window properties
    // Properties
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<EntityInspectorWindow>::from_json(const std::string& json, EntityInspectorWindow& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            // Parent class Window properties
            // Properties
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<EntityInspectorWindow>::to_json(const EntityInspectorWindow& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"EntityInspectorWindow\"" << "," << std::endl;
    // Parent class Window properties
    // Properties
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& EntityInspectorWindow::type_meta() const { return reflect::Type<EntityInspectorWindow>::meta(); }
const char* const EntityInspectorWindow::type_name() const { return reflect::Type<EntityInspectorWindow>::name(); }
const reflect::properties_t& EntityInspectorWindow::type_properties() const { return reflect::Type<EntityInspectorWindow>::properties(); }
EntityInspectorWindow::operator std::string() const { return reflect::Type<EntityInspectorWindow>::to_string(*this); }
void EntityInspectorWindow::from_string(const std::string& str)
{
    reflect::Type<EntityInspectorWindow>::from_string(str, *this);
    type_initialize();
}
void EntityInspectorWindow::from_json(const std::string& json)
{
    reflect::Type<EntityInspectorWindow>::from_json(json, *this);
    type_initialize();
}
std::string EntityInspectorWindow::to_json(const std::string& offset) const { return reflect::Type<EntityInspectorWindow>::to_json(*this, offset); }