// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "performance_window.h"

const meta_t& PerformanceWindow::getTypeMeta() const { return PerformanceWindowType::type().meta; }
const std::string& PerformanceWindow::getTypeName() const { return PerformanceWindowType::type().name; }
const properties_t PerformanceWindow::getTypeProperties() const {
    properties_t properties = Window::getTypeProperties();
    return properties;
}
std::size_t PerformanceWindow::getTypeSize() const { return PerformanceWindowType::type().size; }

const TypeDefinition& PerformanceWindowType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new PerformanceWindow(); }, "PerformanceWindow", {
        std::make_pair("Type", "Window"),
    }, sizeof(PerformanceWindow));
    return s_typeDefinition;
}
