// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SceneWindowType : RegisteredInTypeFactory<SceneWindowType>
{
    SceneWindowType();

    static const meta_t& meta();
    static const char* name();
    static class SceneWindow* const instantiate();
    static bool registered() { return value; };
};

