// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "scene_window.h"

const meta_t& SceneWindow::getTypeMeta() const { return SceneWindowType::type().meta; }
const std::string& SceneWindow::getTypeName() const { return SceneWindowType::type().name; }
const properties_t SceneWindow::getTypeProperties() const {
    properties_t properties = Window::getTypeProperties();
    return properties;
}
std::size_t SceneWindow::getTypeSize() const { return SceneWindowType::type().size; }

const TypeDefinition& SceneWindowType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new SceneWindow(); }, "SceneWindow", {
        std::make_pair("Category", "Window"),
    }, sizeof(SceneWindow));
    return s_typeDefinition;
}
