// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SettingsWindowType
{
    SettingsWindowType();

    static const meta_t& meta();
    static const char* name();
    static class SettingsWindow* const instantiate();
};
extern SettingsWindowType __settingswindow_type;

