// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "bullet_component.h"

const meta_t& BulletComponent::getTypeMeta() const { return BulletComponentType::meta(); }
const char* BulletComponent::getTypeName() const { return BulletComponentType::name(); }
const properties_t BulletComponent::getTypeProperties() const {
    member_address_t origin = reinterpret_cast<member_address_t>(this);
    properties_t properties = Component::getTypeProperties();
    return properties;
}
std::size_t BulletComponent::getTypeSize() const { return sizeof(BulletComponent); }

BulletComponentType::BulletComponentType()
{
    TypeFactoryRegister::load(BulletComponentType::name(), []() -> const meta_t& { return BulletComponentType::meta(); }, []() -> IType* { return BulletComponentType::instantiate(); });
}

BulletComponent* const BulletComponentType::instantiate()
{
    return new BulletComponent();
}

const meta_t& BulletComponentType::meta()
{
    static meta_t s_meta{
    };
    return s_meta;
}

const char* BulletComponentType::name() { return "BulletComponent"; }

