// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct CameraFollow2dComponentType
{
    CameraFollow2dComponentType();

    static const meta_t& meta();
    static const char* name();
    static class CameraFollow2dComponent* const instantiate();
};
extern CameraFollow2dComponentType __camerafollow2dcomponent_type;

