// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct __CameraFollow2dComponentType : RegisteredInTypeFactory<__CameraFollow2dComponentType>
{
    __CameraFollow2dComponentType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

