// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "combat_type.h"

const char* EnumType<CombatType>::name() { return "CombatType"; }
const std::map<const char*, int>  EnumType<CombatType>::values()
{
    static std::map<const char*, int> s_values{
        { "Meele", static_cast<int>(CombatType::Meele) }, 
        { "Ranged", static_cast<int>(CombatType::Ranged) }, 
    };
    return s_values;
}

