// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct LifetimeComponentType
{
    LifetimeComponentType();

    static const meta_t& meta();
    static const char* name();
    static class LifetimeComponent* const instantiate();
};
extern LifetimeComponentType __lifetimecomponent_type;

