// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct MinionControllerComponentType : RegisteredInTypeFactory<MinionControllerComponentType>
{
    MinionControllerComponentType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

