// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct PawnComponentType : RegisteredInTypeFactory<PawnComponentType>
{
    PawnComponentType() = delete;

    static const Type& type();
    static bool registered() { return value; };
};

