// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "pawn_controller_component.h"

const meta_t& PawnControllerComponent::getTypeMeta() const { return PawnControllerComponentType::type().meta; }
const std::string& PawnControllerComponent::getTypeName() const { return PawnControllerComponentType::type().name; }
const properties_t PawnControllerComponent::getTypeProperties() const {
    properties_t properties = Component::getTypeProperties();
    return properties;
}
std::size_t PawnControllerComponent::getTypeSize() const { return PawnControllerComponentType::type().size; }

const Type& PawnControllerComponentType::type()
{
    static const Type s_type([]() -> IType* { return new PawnControllerComponent(); }, "PawnControllerComponent", {
    }, sizeof(PawnControllerComponent));
    return s_type;
}
