// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct RotatorComponentType
{
    RotatorComponentType();

    static const meta_t& meta();
    static const char* name();
    static class RotatorComponent* const instantiate();
};
extern RotatorComponentType __rotatorcomponent_type;

