// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "shoot_component.h"

const meta_t& ShootComponent::getTypeMeta() const { return ShootComponentType::type().meta; }
const std::string& ShootComponent::getTypeName() const { return ShootComponentType::type().name; }
const properties_t ShootComponent::getTypeProperties() const {
    properties_t properties = Component::getTypeProperties();
    return properties;
}
std::size_t ShootComponent::getTypeSize() const { return ShootComponentType::type().size; }

const TypeDefinition& ShootComponentType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new ShootComponent(); }, "ShootComponent", {
        std::make_pair("Category", "Component"),
    }, sizeof(ShootComponent));
    return s_typeDefinition;
}
