// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SpawnerComponentType : RegisteredInTypeFactory<SpawnerComponentType>
{
    SpawnerComponentType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

