// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "color.h"
#pragma warning(disable: 4100)

const reflect::meta_t& reflect::Type<graphics::Color>::meta()
{
    static reflect::meta_t s_meta {
    };
    return s_meta;
}
const char* const reflect::Type<graphics::Color>::name() { return "graphics::Color"; }

const reflect::properties_t& Type<graphics::Color>::properties()
{
    static reflect::properties_t s_properties {
        { "red", reflect::Property{ offsetof(graphics::Color, red), reflect::meta_t { }, "red", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
        { "green", reflect::Property{ offsetof(graphics::Color, green), reflect::meta_t { }, "green", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
        { "blue", reflect::Property{ offsetof(graphics::Color, blue), reflect::meta_t { }, "blue", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
        { "alpha", reflect::Property{ offsetof(graphics::Color, alpha), reflect::meta_t { }, "alpha", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
    };
    return s_properties;
}

std::size_t reflect::Type<graphics::Color>::size()
{
    return sizeof(graphics::Color);
}

void reflect::Type<graphics::Color>::from_string(const std::string& str, graphics::Color& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    stream >> type.red;
    stream >> type.green;
    stream >> type.blue;
    stream >> type.alpha;
}

std::string reflect::Type<graphics::Color>::to_string(const graphics::Color& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    stream << type.red;
    stream << type.green;
    stream << type.blue;
    stream << type.alpha;
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<graphics::Color>::from_json(const std::string& json, graphics::Color& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            if (key == "red") reflect::encoding::json::Deserializer::parse(value, type.red);
            if (key == "green") reflect::encoding::json::Deserializer::parse(value, type.green);
            if (key == "blue") reflect::encoding::json::Deserializer::parse(value, type.blue);
            if (key == "alpha") reflect::encoding::json::Deserializer::parse(value, type.alpha);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<graphics::Color>::to_json(const graphics::Color& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"graphics::Color\"" << "," << std::endl;
    stream << offset << "    " << "\"red\": " << reflect::encoding::json::Serializer::to_string(type.red) << "," << std::endl;
    stream << offset << "    " << "\"green\": " << reflect::encoding::json::Serializer::to_string(type.green) << "," << std::endl;
    stream << offset << "    " << "\"blue\": " << reflect::encoding::json::Serializer::to_string(type.blue) << "," << std::endl;
    stream << offset << "    " << "\"alpha\": " << reflect::encoding::json::Serializer::to_string(type.alpha) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}