// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

namespace graphics
{
    class TextureCoords;
}

template <>
struct reflect::Type<class graphics::TextureCoords>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, graphics::TextureCoords& type);
    static std::string to_string(const graphics::TextureCoords& type);
    static void from_json(const std::string& json, graphics::TextureCoords& type);
    static std::string to_json(const graphics::TextureCoords& type, const std::string& offset = "");
};