// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtproto/runtime.h>

#include "new_scene_menu_item.h"
#include "save_scene_as_menu_item.h"
#include "save_scene_menu_item.h"
#include "show_windows_menu_item.h"
#include "sprite_animation_menu_item.h"
#include "sprite_menu_item.h"

namespace editor
{

class NewSceneMenuItemType
{
public:
    NewSceneMenuItemType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const NewSceneMenuItem* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

class SaveSceneAsMenuItemType
{
public:
    SaveSceneAsMenuItemType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const SaveSceneAsMenuItem* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

class SaveSceneMenuItemType
{
public:
    SaveSceneMenuItemType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const SaveSceneMenuItem* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

class ShowWindowsMenuItemType
{
public:
    ShowWindowsMenuItemType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const ShowWindowsMenuItem* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

class SpriteAnimationMenuItemType
{
public:
    SpriteAnimationMenuItemType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const SpriteAnimationMenuItem* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

class SpriteMenuItemType
{
public:
    SpriteMenuItemType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const SpriteMenuItem* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

} // namespace editor
