// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "new_scene_menu_item.h"

const meta_t& NewSceneMenuItem::getTypeMeta() const { return NewSceneMenuItemType::type().meta; }
const std::string& NewSceneMenuItem::getTypeName() const { return NewSceneMenuItemType::type().name; }
const properties_t NewSceneMenuItem::getTypeProperties() const {
    properties_t properties = MenuItem::getTypeProperties();
    return properties;
}
std::size_t NewSceneMenuItem::getTypeSize() const { return NewSceneMenuItemType::type().size; }

const Type& NewSceneMenuItemType::type()
{
    static const Type s_type([]() -> IType* { return new NewSceneMenuItem(); }, "NewSceneMenuItem", {
    }, sizeof(NewSceneMenuItem));
    return s_type;
}
