// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "new_scene_menu_item.h"

const meta_t& NewSceneMenuItem::getTypeMeta() const { return NewSceneMenuItemType::meta(); }
const char* NewSceneMenuItem::getTypeName() const { return NewSceneMenuItemType::name(); }
const properties_t NewSceneMenuItem::getTypeProperties() const {
    member_address_t origin = reinterpret_cast<member_address_t>(this);
    properties_t properties = MenuItem::getTypeProperties();
    return properties;
}
std::size_t NewSceneMenuItem::getTypeSize() const { return sizeof(NewSceneMenuItem); }

NewSceneMenuItemType::NewSceneMenuItemType()
{
    TypeFactoryRegister::load(NewSceneMenuItemType::name(), []() -> const meta_t& { return NewSceneMenuItemType::meta(); }, []() -> IType* { return NewSceneMenuItemType::instantiate(); });
}

NewSceneMenuItem* const NewSceneMenuItemType::instantiate()
{
    return new NewSceneMenuItem();
}

const meta_t& NewSceneMenuItemType::meta()
{
    static meta_t s_meta{
    };
    return s_meta;
}

const char* NewSceneMenuItemType::name() { return "NewSceneMenuItem"; }

