// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "save_scene_menu_item.h"

const meta_t& SaveSceneMenuItem::getTypeMeta() const { return SaveSceneMenuItemType::type().meta; }
const std::string& SaveSceneMenuItem::getTypeName() const { return SaveSceneMenuItemType::type().name; }
const properties_t SaveSceneMenuItem::getTypeProperties() const {
    member_address_t origin = reinterpret_cast<member_address_t>(this);
    properties_t properties = MenuItem::getTypeProperties();
    return properties;
}
std::size_t SaveSceneMenuItem::getTypeSize() const { return SaveSceneMenuItemType::type().size; }

const Type& SaveSceneMenuItemType::type()
{
    static const Type s_type([]() -> IType* { return new SaveSceneMenuItem(); }, "SaveSceneMenuItem", {
    }, sizeof(SaveSceneMenuItem));
    return s_type;
}
