// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "save_scene_menu_item.h"

const meta_t& SaveSceneMenuItem::getTypeMeta() const { return SaveSceneMenuItemType::type().meta; }
const std::string& SaveSceneMenuItem::getTypeName() const { return SaveSceneMenuItemType::type().name; }
const properties_t SaveSceneMenuItem::getTypeProperties() const {
    properties_t properties = MenuItem::getTypeProperties();
    return properties;
}
std::size_t SaveSceneMenuItem::getTypeSize() const { return SaveSceneMenuItemType::type().size; }

const TypeDefinition& SaveSceneMenuItemType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> IType* { return new SaveSceneMenuItem(); }, "SaveSceneMenuItem", {
        std::make_pair("Category", "MenuItem"),
    }, sizeof(SaveSceneMenuItem));
    return s_typeDefinition;
}
