// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "show_windows_menu_item.h"

const meta_t& ShowWindowsMenuItem::getTypeMeta() const { return ShowWindowsMenuItemType::type().meta; }
const std::string& ShowWindowsMenuItem::getTypeName() const { return ShowWindowsMenuItemType::type().name; }
const properties_t ShowWindowsMenuItem::getTypeProperties() const {
    properties_t properties = MenuItem::getTypeProperties();
    return properties;
}
std::size_t ShowWindowsMenuItem::getTypeSize() const { return ShowWindowsMenuItemType::type().size; }

const Type& ShowWindowsMenuItemType::type()
{
    static const Type s_type([]() -> IType* { return new ShowWindowsMenuItem(); }, "ShowWindowsMenuItem", {
    }, sizeof(ShowWindowsMenuItem));
    return s_type;
}
