// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SpriteAnimationMenuItemType
{
    SpriteAnimationMenuItemType();

    static const meta_t& meta();
    static const char* name();
    static class SpriteAnimationMenuItem* const instantiate();
};
extern SpriteAnimationMenuItemType __spriteanimationmenuitem_type;

