// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SpriteMenuItemType
{
    SpriteMenuItemType();

    static const meta_t& meta();
    static const char* name();
    static class SpriteMenuItem* const instantiate();
};
extern SpriteMenuItemType __spritemenuitem_type;

