// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SpriteMenuItemType : RegisteredInTypeFactory<SpriteMenuItemType>
{
    SpriteMenuItemType();

    static const meta_t& meta();
    static const char* name();
    static class SpriteMenuItem* const instantiate();
    static bool registered() { return value; };
};

