// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "sprite_animation_menu_item.h"

const meta_t& SpriteAnimationMenuItem::getTypeMeta() const { return SpriteAnimationMenuItemType::type().meta; }
const std::string& SpriteAnimationMenuItem::getTypeName() const { return SpriteAnimationMenuItemType::type().name; }
const properties_t SpriteAnimationMenuItem::getTypeProperties() const {
    properties_t properties = MenuItem::getTypeProperties();
    return properties;
}
std::size_t SpriteAnimationMenuItem::getTypeSize() const { return SpriteAnimationMenuItemType::type().size; }

const Type& SpriteAnimationMenuItemType::type()
{
    static const Type s_type([]() -> IType* { return new SpriteAnimationMenuItem(); }, "SpriteAnimationMenuItem", {
        std::make_pair("Category", "MenuItem"),
    }, sizeof(SpriteAnimationMenuItem));
    return s_type;
}
