// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "tileset_menu_item.h"

const meta_t& TilesetMenuItem::getTypeMeta() const { return TilesetMenuItemType::type().meta; }
const std::string& TilesetMenuItem::getTypeName() const { return TilesetMenuItemType::type().name; }
const properties_t TilesetMenuItem::getTypeProperties() const {
    properties_t properties = MenuItem::getTypeProperties();
    return properties;
}
std::size_t TilesetMenuItem::getTypeSize() const { return TilesetMenuItemType::type().size; }

const TypeDefinition& TilesetMenuItemType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new TilesetMenuItem(); }, "TilesetMenuItem", {
        std::make_pair("Category", "MenuItem"),
    }, sizeof(TilesetMenuItem));
    return s_typeDefinition;
}
