// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "component.h"

const type_meta_t& Type<Component>::meta()
{
    static type_meta_t s_meta {
    };
    return s_meta;
}
const char* const Type<Component>::name() { return "Component"; }

const type_properties_t& Type<Component>::properties()
{
    static type_properties_t s_properties {
    };
    return s_properties;
}

const type_meta_t& Component::type_meta() const { return Type<Component>::meta(); }
const char* const Component::type_name() const { return Type<Component>::name(); }
const type_properties_t& Component::type_properties() const { return Type<Component>::properties(); }

