// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Type<class Component> : reflect::RegisteredInTypeFactory<class Component>
{
    static IType* const instantiate();
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, Component& type);
    static std::string to_string(const Component& type);
    static void from_json(const std::string& json, Component& type);
    static std::string to_json(const Component& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};