// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "shape_type.h"

const char* EnumType<ShapeType>::name() { return "ShapeType"; }
const enum_values_t& EnumType<ShapeType>::values()
{
    static enum_values_t s_values{
        { "None", static_cast<int>(ShapeType::None) }, 
        { "Circle", static_cast<int>(ShapeType::Circle) }, 
        { "Rect", static_cast<int>(ShapeType::Rect) }, 
    };
    return s_values;
}

