// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "camera_follow2d_component.h"
#pragma warning(disable: 4100)

const reflect::meta_t& reflect::Type<CameraFollow2dComponent>::meta()
{
    static reflect::meta_t s_meta {
        { "Type", "Component" },
    };
    return s_meta;
}
const char* const reflect::Type<CameraFollow2dComponent>::name() { return "CameraFollow2dComponent"; }

const reflect::properties_t& Type<CameraFollow2dComponent>::properties()
{
    static reflect::properties_t s_properties {
        // Parent class Component properties
        { "enabled", reflect::Property{ offsetof(CameraFollow2dComponent, enabled), reflect::meta_t { }, "enabled", reflect::PropertyType{ "bool", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(bool), reflect::PropertyType::Type::T_bool } } },
        { "m_id", reflect::Property{ offsetof(CameraFollow2dComponent, m_id), reflect::meta_t { }, "m_id", reflect::PropertyType{ "uuid", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(uuid), reflect::PropertyType::Type::T_type } } },
        // Properties
        { "m_speed", reflect::Property{ offsetof(CameraFollow2dComponent, m_speed), reflect::meta_t { }, "m_speed", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
        { "m_targetTag", reflect::Property{ offsetof(CameraFollow2dComponent, m_targetTag), reflect::meta_t { }, "m_targetTag", reflect::PropertyType{ "std::string", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(std::string), reflect::PropertyType::Type::T_string } } },
    };
    return s_properties;
}

std::size_t reflect::Type<CameraFollow2dComponent>::size()
{
    return sizeof(CameraFollow2dComponent);
}

void reflect::Type<CameraFollow2dComponent>::from_string(const std::string& str, CameraFollow2dComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    // Parent class Component properties
    stream >> type.enabled;
    {
        std::string pack;
        stream >> pack;
        type.m_id.from_string(pack);
    }
    // Properties
    stream >> type.m_speed;
    stream >> type.m_targetTag;
}

std::string reflect::Type<CameraFollow2dComponent>::to_string(const CameraFollow2dComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    // Parent class Component properties
    stream << type.enabled;
    stream << static_cast<std::string>(type.m_id);
    // Properties
    stream << type.m_speed;
    stream << type.m_targetTag;
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<CameraFollow2dComponent>::from_json(const std::string& json, CameraFollow2dComponent& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            // Parent class Component properties
            if (key == "enabled") reflect::encoding::json::Deserializer::parse(value, type.enabled);
            if (key == "m_id") type.m_id.from_json(value);
            // Properties
            if (key == "m_speed") reflect::encoding::json::Deserializer::parse(value, type.m_speed);
            if (key == "m_targetTag") reflect::encoding::json::Deserializer::parse(value, type.m_targetTag);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<CameraFollow2dComponent>::to_json(const CameraFollow2dComponent& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"CameraFollow2dComponent\"" << "," << std::endl;
    // Parent class Component properties
    stream << offset << "    " << "\"enabled\": " << reflect::encoding::json::Serializer::to_string(type.enabled) << "," << std::endl;
    stream << offset << "    " << "\"m_id\": " << type.m_id.to_json(offset + "    ") << "," << std::endl;
    // Properties
    stream << offset << "    " << "\"m_speed\": " << reflect::encoding::json::Serializer::to_string(type.m_speed) << "," << std::endl;
    stream << offset << "    " << "\"m_targetTag\": " << reflect::encoding::json::Serializer::to_string(type.m_targetTag) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& CameraFollow2dComponent::type_meta() const { return reflect::Type<CameraFollow2dComponent>::meta(); }
const char* const CameraFollow2dComponent::type_name() const { return reflect::Type<CameraFollow2dComponent>::name(); }
const reflect::properties_t& CameraFollow2dComponent::type_properties() const { return reflect::Type<CameraFollow2dComponent>::properties(); }
CameraFollow2dComponent::operator std::string() const { return reflect::Type<CameraFollow2dComponent>::to_string(*this); }
void CameraFollow2dComponent::from_string(const std::string& str)
{
    reflect::Type<CameraFollow2dComponent>::from_string(str, *this);
    type_initialize();
}
void CameraFollow2dComponent::from_json(const std::string& json)
{
    reflect::Type<CameraFollow2dComponent>::from_json(json, *this);
    type_initialize();
}
std::string CameraFollow2dComponent::to_json(const std::string& offset) const { return reflect::Type<CameraFollow2dComponent>::to_json(*this, offset); }