// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "camera_controller2d_component.h"
#pragma warning(disable: 4100)

IType* const reflect::Type<CameraController2DComponent>::instantiate()
{
    return dynamic_cast<IType*>(new CameraController2DComponent());
}

const reflect::meta_t& reflect::Type<CameraController2DComponent>::meta()
{
    static reflect::meta_t s_meta {
        { "Type", "Component" },
    };
    return s_meta;
}
const char* const reflect::Type<CameraController2DComponent>::name() { return "CameraController2DComponent"; }

const reflect::properties_t& Type<CameraController2DComponent>::properties()
{
    static reflect::properties_t s_properties {
        // Parent class Component properties
        { "enabled", reflect::Property{ offsetof(CameraController2DComponent, enabled), reflect::meta_t { }, "enabled", reflect::PropertyType{ "bool", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(bool), reflect::PropertyType::Type::T_bool } } },
        { "m_id", reflect::Property{ offsetof(CameraController2DComponent, m_id), reflect::meta_t { }, "m_id", reflect::PropertyType{ "uuid", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(uuid), reflect::PropertyType::Type::T_type } } },
        // Properties
        { "speed", reflect::Property{ offsetof(CameraController2DComponent, speed), reflect::meta_t { }, "speed", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
        { "zoomSpeed", reflect::Property{ offsetof(CameraController2DComponent, zoomSpeed), reflect::meta_t { }, "zoomSpeed", reflect::PropertyType{ "float", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(float), reflect::PropertyType::Type::T_float } } },
    };
    return s_properties;
}

std::size_t reflect::Type<CameraController2DComponent>::size()
{
    return sizeof(CameraController2DComponent);
}

void reflect::Type<CameraController2DComponent>::from_string(const std::string& str, CameraController2DComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    // Parent class Component properties
    stream >> type.enabled;
    {
        std::string pack;
        stream >> pack;
        type.m_id.from_string(pack);
    }
    // Properties
    stream >> type.speed;
    stream >> type.zoomSpeed;
}

std::string reflect::Type<CameraController2DComponent>::to_string(const CameraController2DComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    // Parent class Component properties
    stream << type.enabled;
    stream << static_cast<std::string>(type.m_id);
    // Properties
    stream << type.speed;
    stream << type.zoomSpeed;
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<CameraController2DComponent>::from_json(const std::string& json, CameraController2DComponent& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            // Parent class Component properties
            if (key == "enabled") reflect::encoding::json::Deserializer::parse(value, type.enabled);
            if (key == "m_id") type.m_id.from_json(value);
            // Properties
            if (key == "speed") reflect::encoding::json::Deserializer::parse(value, type.speed);
            if (key == "zoomSpeed") reflect::encoding::json::Deserializer::parse(value, type.zoomSpeed);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<CameraController2DComponent>::to_json(const CameraController2DComponent& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"CameraController2DComponent\"" << "," << std::endl;
    // Parent class Component properties
    stream << offset << "    " << "\"enabled\": " << reflect::encoding::json::Serializer::to_string(type.enabled) << "," << std::endl;
    stream << offset << "    " << "\"m_id\": " << type.m_id.to_json(offset + "    ") << "," << std::endl;
    // Properties
    stream << offset << "    " << "\"speed\": " << reflect::encoding::json::Serializer::to_string(type.speed) << "," << std::endl;
    stream << offset << "    " << "\"zoomSpeed\": " << reflect::encoding::json::Serializer::to_string(type.zoomSpeed) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& CameraController2DComponent::type_meta() const { return reflect::Type<CameraController2DComponent>::meta(); }
const char* const CameraController2DComponent::type_name() const { return reflect::Type<CameraController2DComponent>::name(); }
const reflect::properties_t& CameraController2DComponent::type_properties() const { return reflect::Type<CameraController2DComponent>::properties(); }
CameraController2DComponent::operator std::string() const { return reflect::Type<CameraController2DComponent>::to_string(*this); }
void CameraController2DComponent::from_string(const std::string& str)
{
    reflect::Type<CameraController2DComponent>::from_string(str, *this);
    type_initialize();
}
void CameraController2DComponent::from_json(const std::string& json)
{
    reflect::Type<CameraController2DComponent>::from_json(json, *this);
    type_initialize();
}
std::string CameraController2DComponent::to_json(const std::string& offset) const { return reflect::Type<CameraController2DComponent>::to_json(*this, offset); }