// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Enum<enum class Collision2DShapeType> : reflect::RegisteredInEnumFactory<enum class Collision2DShapeType>
{
    static const char* const name();
    static const reflect::enum_values_t& values();
    
    static bool registered() { return value; };
};

template <>
struct reflect::Type<class Collider2DComponent> : reflect::RegisteredInTypeFactory<class Collider2DComponent>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, Collider2DComponent& type);
    static std::string to_string(const Collider2DComponent& type);
    static void from_json(const std::string& json, Collider2DComponent& type);
    static std::string to_json(const Collider2DComponent& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};