// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "lifetime_component.h"
#pragma warning(disable: 4100)

IType* const reflect::Type<LifetimeComponent>::instantiate()
{
    return dynamic_cast<IType*>(new LifetimeComponent());
}

const reflect::meta_t& reflect::Type<LifetimeComponent>::meta()
{
    static reflect::meta_t s_meta {
        { "Type", "Component" },
    };
    return s_meta;
}
const char* const reflect::Type<LifetimeComponent>::name() { return "LifetimeComponent"; }

const reflect::properties_t& Type<LifetimeComponent>::properties()
{
    static reflect::properties_t s_properties {
        // Parent class Component properties
        { "enabled", reflect::Property{ offsetof(LifetimeComponent, enabled), reflect::meta_t { }, "enabled", reflect::PropertyType{ "bool", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(bool), reflect::PropertyType::Type::T_bool } } },
        { "m_id", reflect::Property{ offsetof(LifetimeComponent, m_id), reflect::meta_t { }, "m_id", reflect::PropertyType{ "uuid", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(uuid), reflect::PropertyType::Type::T_type } } },
        // Properties
        { "lifetime", reflect::Property{ offsetof(LifetimeComponent, lifetime), reflect::meta_t { }, "lifetime", reflect::PropertyType{ "double", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(double), reflect::PropertyType::Type::T_double } } },
    };
    return s_properties;
}

std::size_t reflect::Type<LifetimeComponent>::size()
{
    return sizeof(LifetimeComponent);
}

void reflect::Type<LifetimeComponent>::from_string(const std::string& str, LifetimeComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    // Parent class Component properties
    stream >> type.enabled;
    {
        std::string pack;
        stream >> pack;
        type.m_id.from_string(pack);
    }
    // Properties
    stream >> type.lifetime;
}

std::string reflect::Type<LifetimeComponent>::to_string(const LifetimeComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    // Parent class Component properties
    stream << type.enabled;
    stream << static_cast<std::string>(type.m_id);
    // Properties
    stream << type.lifetime;
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<LifetimeComponent>::from_json(const std::string& json, LifetimeComponent& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            // Parent class Component properties
            if (key == "enabled") reflect::encoding::json::Deserializer::parse(value, type.enabled);
            if (key == "m_id") type.m_id.from_json(value);
            // Properties
            if (key == "lifetime") reflect::encoding::json::Deserializer::parse(value, type.lifetime);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<LifetimeComponent>::to_json(const LifetimeComponent& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"LifetimeComponent\"" << "," << std::endl;
    // Parent class Component properties
    stream << offset << "    " << "\"enabled\": " << reflect::encoding::json::Serializer::to_string(type.enabled) << "," << std::endl;
    stream << offset << "    " << "\"m_id\": " << type.m_id.to_json(offset + "    ") << "," << std::endl;
    // Properties
    stream << offset << "    " << "\"lifetime\": " << reflect::encoding::json::Serializer::to_string(type.lifetime) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& LifetimeComponent::type_meta() const { return reflect::Type<LifetimeComponent>::meta(); }
const char* const LifetimeComponent::type_name() const { return reflect::Type<LifetimeComponent>::name(); }
const reflect::properties_t& LifetimeComponent::type_properties() const { return reflect::Type<LifetimeComponent>::properties(); }
LifetimeComponent::operator std::string() const { return reflect::Type<LifetimeComponent>::to_string(*this); }
void LifetimeComponent::from_string(const std::string& str)
{
    reflect::Type<LifetimeComponent>::from_string(str, *this);
    type_initialize();
}
void LifetimeComponent::from_json(const std::string& json)
{
    reflect::Type<LifetimeComponent>::from_json(json, *this);
    type_initialize();
}
std::string LifetimeComponent::to_json(const std::string& offset) const { return reflect::Type<LifetimeComponent>::to_json(*this, offset); }