// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Enum<enum class RigidbodyType2D> : reflect::RegisteredInEnumFactory<enum class RigidbodyType2D>
{
    static const char* const name();
    static const reflect::enum_values_t& values();
    
    static bool registered() { return value; };
};

template <>
struct reflect::Type<class Rigidbody2DComponent> : reflect::RegisteredInTypeFactory<class Rigidbody2DComponent>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, Rigidbody2DComponent& type);
    static std::string to_string(const Rigidbody2DComponent& type);
    static void from_json(const std::string& json, Rigidbody2DComponent& type);
    static std::string to_json(const Rigidbody2DComponent& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};