// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "sprite_renderer_component.h"
#pragma warning(disable: 4100)

const reflect::meta_t& reflect::Type<SpriteRendererComponent>::meta()
{
    static reflect::meta_t s_meta {
        { "Category", "Graphics" },
        { "Type", "Component" },
    };
    return s_meta;
}
const char* const reflect::Type<SpriteRendererComponent>::name() { return "SpriteRendererComponent"; }

const reflect::properties_t& Type<SpriteRendererComponent>::properties()
{
    static reflect::properties_t s_properties {
        // Parent class Component properties
        { "enabled", reflect::Property{ offsetof(SpriteRendererComponent, enabled), reflect::meta_t { }, "enabled", reflect::PropertyType{ "bool", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(bool), reflect::PropertyType::Type::T_bool } } },
        { "m_id", reflect::Property{ offsetof(SpriteRendererComponent, m_id), reflect::meta_t { }, "m_id", reflect::PropertyType{ "uuid", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(uuid), reflect::PropertyType::Type::T_type } } },
        // Properties
        { "rect", reflect::Property{ offsetof(SpriteRendererComponent, rect), reflect::meta_t { }, "rect", reflect::PropertyType{ "graphics::TextureRect", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(graphics::TextureRect), reflect::PropertyType::Type::T_native } } },
        { "color", reflect::Property{ offsetof(SpriteRendererComponent, color), reflect::meta_t { }, "color", reflect::PropertyType{ "graphics::Color", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(graphics::Color), reflect::PropertyType::Type::T_native } } },
        { "flipX", reflect::Property{ offsetof(SpriteRendererComponent, flipX), reflect::meta_t { }, "flipX", reflect::PropertyType{ "bool", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(bool), reflect::PropertyType::Type::T_bool } } },
        { "flipY", reflect::Property{ offsetof(SpriteRendererComponent, flipY), reflect::meta_t { }, "flipY", reflect::PropertyType{ "bool", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(bool), reflect::PropertyType::Type::T_bool } } },
        { "image", reflect::Property{ offsetof(SpriteRendererComponent, image), reflect::meta_t { }, "image", reflect::PropertyType{ "ImageAsset", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(ImageAsset), reflect::PropertyType::Type::T_type } } },
    };
    return s_properties;
}

std::size_t reflect::Type<SpriteRendererComponent>::size()
{
    return sizeof(SpriteRendererComponent);
}

void reflect::Type<SpriteRendererComponent>::from_string(const std::string& str, SpriteRendererComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    // Parent class Component properties
    stream >> type.enabled;
    {
        std::string pack;
        stream >> pack;
        type.m_id.from_string(pack);
    }
    // Properties
    {
        std::string pack;
        stream >> pack;
        reflect::Type<graphics::TextureRect>::from_string(pack, type.rect);
    }
    {
        std::string pack;
        stream >> pack;
        reflect::Type<graphics::Color>::from_string(pack, type.color);
    }
    stream >> type.flipX;
    stream >> type.flipY;
    {
        std::string pack;
        stream >> pack;
        type.image.from_string(pack);
    }
}

std::string reflect::Type<SpriteRendererComponent>::to_string(const SpriteRendererComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    // Parent class Component properties
    stream << type.enabled;
    stream << static_cast<std::string>(type.m_id);
    // Properties
    stream << reflect::Type<graphics::TextureRect>::to_string(type.rect);
    stream << reflect::Type<graphics::Color>::to_string(type.color);
    stream << type.flipX;
    stream << type.flipY;
    stream << static_cast<std::string>(type.image);
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<SpriteRendererComponent>::from_json(const std::string& json, SpriteRendererComponent& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            // Parent class Component properties
            if (key == "enabled") reflect::encoding::json::Deserializer::parse(value, type.enabled);
            if (key == "m_id") type.m_id.from_json(value);
            // Properties
            if (key == "rect") reflect::Type<graphics::TextureRect>::from_json(value, type.rect);
            if (key == "color") reflect::Type<graphics::Color>::from_json(value, type.color);
            if (key == "flipX") reflect::encoding::json::Deserializer::parse(value, type.flipX);
            if (key == "flipY") reflect::encoding::json::Deserializer::parse(value, type.flipY);
            if (key == "image") type.image.from_json(value);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<SpriteRendererComponent>::to_json(const SpriteRendererComponent& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"SpriteRendererComponent\"" << "," << std::endl;
    // Parent class Component properties
    stream << offset << "    " << "\"enabled\": " << reflect::encoding::json::Serializer::to_string(type.enabled) << "," << std::endl;
    stream << offset << "    " << "\"m_id\": " << type.m_id.to_json(offset + "    ") << "," << std::endl;
    // Properties
    stream << offset << "    " << "\"rect\": " << reflect::Type<graphics::TextureRect>::to_json(type.rect, offset + "    ") << "," << std::endl;
    stream << offset << "    " << "\"color\": " << reflect::Type<graphics::Color>::to_json(type.color, offset + "    ") << "," << std::endl;
    stream << offset << "    " << "\"flipX\": " << reflect::encoding::json::Serializer::to_string(type.flipX) << "," << std::endl;
    stream << offset << "    " << "\"flipY\": " << reflect::encoding::json::Serializer::to_string(type.flipY) << "," << std::endl;
    stream << offset << "    " << "\"image\": " << type.image.to_json(offset + "    ") << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& SpriteRendererComponent::type_meta() const { return reflect::Type<SpriteRendererComponent>::meta(); }
const char* const SpriteRendererComponent::type_name() const { return reflect::Type<SpriteRendererComponent>::name(); }
const reflect::properties_t& SpriteRendererComponent::type_properties() const { return reflect::Type<SpriteRendererComponent>::properties(); }
SpriteRendererComponent::operator std::string() const { return reflect::Type<SpriteRendererComponent>::to_string(*this); }
void SpriteRendererComponent::from_string(const std::string& str)
{
    reflect::Type<SpriteRendererComponent>::from_string(str, *this);
    type_initialize();
}
void SpriteRendererComponent::from_json(const std::string& json)
{
    reflect::Type<SpriteRendererComponent>::from_json(json, *this);
    type_initialize();
}
std::string SpriteRendererComponent::to_json(const std::string& offset) const { return reflect::Type<SpriteRendererComponent>::to_json(*this, offset); }