// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "sprite_animator_component.h"
#pragma warning(disable: 4100)

const reflect::meta_t& reflect::Type<SpriteAnimatorComponent>::meta()
{
    static reflect::meta_t s_meta {
        { "Type", "Component" },
    };
    return s_meta;
}
const char* const reflect::Type<SpriteAnimatorComponent>::name() { return "SpriteAnimatorComponent"; }

const reflect::properties_t& Type<SpriteAnimatorComponent>::properties()
{
    static reflect::properties_t s_properties {
        // Parent class Component properties
        { "enabled", reflect::Property{ offsetof(SpriteAnimatorComponent, enabled), reflect::meta_t { }, "enabled", reflect::PropertyType{ "bool", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(bool), reflect::PropertyType::Type::T_bool } } },
        { "m_id", reflect::Property{ offsetof(SpriteAnimatorComponent, m_id), reflect::meta_t { }, "m_id", reflect::PropertyType{ "uuid", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(uuid), reflect::PropertyType::Type::T_type } } },
        // Properties
        { "animations", reflect::Property{ offsetof(SpriteAnimatorComponent, animations), reflect::meta_t { }, "animations", reflect::PropertyType{ "std::map<std::string, SpriteAnimationAsset>", { 
            reflect::PropertyType{ "std::string", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(std::string), reflect::PropertyType::Type::T_string },
            reflect::PropertyType{ "SpriteAnimationAsset", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(SpriteAnimationAsset), reflect::PropertyType::Type::T_type },
        }, reflect::PropertyType::DecoratorType::D_raw, sizeof(std::map<std::string, SpriteAnimationAsset>), reflect::PropertyType::Type::T_template } } },
        { "autoplay", reflect::Property{ offsetof(SpriteAnimatorComponent, autoplay), reflect::meta_t { }, "autoplay", reflect::PropertyType{ "bool", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(bool), reflect::PropertyType::Type::T_bool } } },
    };
    return s_properties;
}

std::size_t reflect::Type<SpriteAnimatorComponent>::size()
{
    return sizeof(SpriteAnimatorComponent);
}

void reflect::Type<SpriteAnimatorComponent>::from_string(const std::string& str, SpriteAnimatorComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    // Parent class Component properties
    stream >> type.enabled;
    {
        std::string pack;
        stream >> pack;
        type.m_id.from_string(pack);
    }
    // Properties
    {
        std::size_t size;
        stream >> size;
        for (int i = 0; i < size; ++i)
        {
            std::string key;
            stream >> key;
            SpriteAnimationAsset value;
            {
                std::string pack;
                stream >> pack;
                value.from_string(pack);
            }
            type.animations.insert(std::make_pair(key, value));
        }
    }
    stream >> type.autoplay;
}

std::string reflect::Type<SpriteAnimatorComponent>::to_string(const SpriteAnimatorComponent& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    // Parent class Component properties
    stream << type.enabled;
    stream << static_cast<std::string>(type.m_id);
    // Properties
    {
        stream << type.animations.size();
        for (const auto& pair : type.animations)
        {
            stream << pair.first;
            stream << static_cast<std::string>(pair.second);
        }
    }
    stream << type.autoplay;
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<SpriteAnimatorComponent>::from_json(const std::string& json, SpriteAnimatorComponent& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            // Parent class Component properties
            if (key == "enabled") reflect::encoding::json::Deserializer::parse(value, type.enabled);
            if (key == "m_id") type.m_id.from_json(value);
            // Properties
            if (key == "animations") reflect::encoding::json::Deserializer::parse(value, type.animations);
            if (key == "autoplay") reflect::encoding::json::Deserializer::parse(value, type.autoplay);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<SpriteAnimatorComponent>::to_json(const SpriteAnimatorComponent& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"SpriteAnimatorComponent\"" << "," << std::endl;
    // Parent class Component properties
    stream << offset << "    " << "\"enabled\": " << reflect::encoding::json::Serializer::to_string(type.enabled) << "," << std::endl;
    stream << offset << "    " << "\"m_id\": " << type.m_id.to_json(offset + "    ") << "," << std::endl;
    // Properties
    stream << offset << "    " << "\"animations\": " << reflect::encoding::json::Serializer::to_string(type.animations) << "," << std::endl;
    stream << offset << "    " << "\"autoplay\": " << reflect::encoding::json::Serializer::to_string(type.autoplay) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& SpriteAnimatorComponent::type_meta() const { return reflect::Type<SpriteAnimatorComponent>::meta(); }
const char* const SpriteAnimatorComponent::type_name() const { return reflect::Type<SpriteAnimatorComponent>::name(); }
const reflect::properties_t& SpriteAnimatorComponent::type_properties() const { return reflect::Type<SpriteAnimatorComponent>::properties(); }
SpriteAnimatorComponent::operator std::string() const { return reflect::Type<SpriteAnimatorComponent>::to_string(*this); }
void SpriteAnimatorComponent::from_string(const std::string& str)
{
    reflect::Type<SpriteAnimatorComponent>::from_string(str, *this);
    type_initialize();
}
void SpriteAnimatorComponent::from_json(const std::string& json)
{
    reflect::Type<SpriteAnimatorComponent>::from_json(json, *this);
    type_initialize();
}
std::string SpriteAnimatorComponent::to_json(const std::string& offset) const { return reflect::Type<SpriteAnimatorComponent>::to_json(*this, offset); }