// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtproto/runtime.h>

#include "asset_serializer.h"
#include "graphics_serializer.h"
#include "math_serializer.h"
#include "uuid_serializer.h"

class AssetSerializerType
{
public:
    AssetSerializerType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const AssetSerializer* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

class GraphicsSerializerType
{
public:
    GraphicsSerializerType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const GraphicsSerializer* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

class MathSerializerType
{
public:
    MathSerializerType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const MathSerializer* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

class UuidSerializerType
{
public:
    UuidSerializerType() = delete;

    static const TypeDescriptor& descriptor();
    static fields_t fields(const UuidSerializer* const pointer);

private:
    static TypeDescriptor s_typeDescriptor;
    static void registerTypeDescriptor(TypeDescriptor*);
};

