// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <filesystem>
#include <memory>

#include <awesome/asset/scene_asset.h>
#include <awesome/core/type_name.h>
#include <awesome/graphics/color.h>
#include <awesome/player/player_controller.h>

#include "application_settings_generated.h"

ENUM()
enum class ApplicationMode : int
{
    Editor = 0,
    Server = 1,
    Standalone = 2,
};

ENUM()
enum class FpsMode : int
{
    Fps30 = 30,
    Fps60 = 60,
    Fps90 = 90,
    Unlimited,
};

CLASS()
struct ApplicationEditorSettings : public Type
{


    GENERATED_BODY()
};

CLASS()
struct ApplicationDebugSettings : public Type
{
    PROPERTY() bool wireframesEnabled{ true };
    PROPERTY() graphics::Color wireframesColor{ graphics::Color::White };

    GENERATED_BODY()
};

CLASS()
struct ApplicationNetworkSettings : public Type
{
    PROPERTY() int maxServerConnections{ 20 };
    PROPERTY() std::string serverIp;
    PROPERTY() int serverPort{ 96000 };

    GENERATED_BODY()
};

CLASS()
struct ApplicationPlayerSettings : public Type
{
    PROPERTY() TypeName<PlayerController> playerControllerType;
    PROPERTY() TypeName<PlayerState> playerStateType;

    GENERATED_BODY()
};

CLASS()
struct ApplicationSceneSettings : public Type
{
    PROPERTY() SceneAssetPtr editorScene;
    PROPERTY() SceneAssetPtr serverScene;
    PROPERTY() SceneAssetPtr standaloneScene;

    GENERATED_BODY()
};

CLASS()
class ApplicationSettings : public Type
{
public:
    ApplicationSettings() = default;

    static constexpr char* filename{ "settings.json" };

    PROPERTY() std::unique_ptr<ApplicationDebugSettings> debug;
    PROPERTY() std::unique_ptr<ApplicationEditorSettings> editor;
    PROPERTY() FpsMode fps { FpsMode::Fps60 };
    PROPERTY() ApplicationMode mode { ApplicationMode::Editor };
    PROPERTY() std::unique_ptr<ApplicationNetworkSettings> network;
    PROPERTY() std::unique_ptr<ApplicationPlayerSettings> player;
    PROPERTY() int quadspaceBounds{ 100 };
    PROPERTY() std::unique_ptr<ApplicationSceneSettings> scene;
    PROPERTY() std::filesystem::path workspacePath{ std::filesystem::current_path() / ".." / "assets" };

    GENERATED_BODY()
};
