// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "prefab_asset.h"

const reflect::meta_t& reflect::Type<PrefabAsset>::meta()
{
    static reflect::meta_t s_meta {
        { "forward_declaration", "typedef AssetHandle<4 , Prefab , ResourceLoader<Prefab>> PrefabAsset;" },
    };
    return s_meta;
}
const char* const reflect::Type<PrefabAsset>::name() { return "PrefabAsset"; }

const reflect::properties_t& Type<PrefabAsset>::properties()
{
    static reflect::properties_t s_properties {
        { "id", reflect::Property{ offsetof(PrefabAsset, id), reflect::meta_t { }, "id", reflect::PropertyType{ "uuid", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(uuid), reflect::PropertyType::Type::T_type } } },
    };
    return s_properties;
}

std::size_t reflect::Type<PrefabAsset>::size()
{
    return sizeof(PrefabAsset);
}

void reflect::Type<PrefabAsset>::from_string(const std::string& str, PrefabAsset& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    {
        std::string pack;
        stream >> pack;
        type.id.from_string(pack);
    }
}

std::string reflect::Type<PrefabAsset>::to_string(const PrefabAsset& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    stream << static_cast<std::string>(type.id);
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<PrefabAsset>::from_json(const std::string& json, PrefabAsset& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            if (key == "id") type.id.from_json(value);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<PrefabAsset>::to_json(const PrefabAsset& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"PrefabAsset\"" << "," << std::endl;
    stream << offset << "    " << "\"id\": " << type.id.to_json(offset + "    ") << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}