// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

#include "asset_type_generated.h"

ENUM()
enum class AssetType : int
{
    None = 0,
    Image = 1,
    Prefab = 2,
    Scene = 3,
    Sprite = 4,
    SpriteAnimation = 5,
    Text = 6,
};