// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "asset_identifier.h"

const meta_t& AssetIdentifier::getTypeMeta() const { return __AssetIdentifierType::type().meta; }
const std::string& AssetIdentifier::getTypeName() const { return __AssetIdentifierType::type().name; }
const properties_t AssetIdentifier::getTypeProperties() const {
    properties_t properties;
    return properties;
}
std::size_t AssetIdentifier::getTypeSize() const { return __AssetIdentifierType::type().size; }
const meta_t& AssetIdentifier::staticTypeMeta() { return __AssetIdentifierType::type().meta; }
const std::string& AssetIdentifier::staticTypeName() { return __AssetIdentifierType::type().name; }

const TypeDefinition& __AssetIdentifierType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new AssetIdentifier(); }, "AssetIdentifier", {
    }, sizeof(AssetIdentifier));
    return s_typeDefinition;
}
