// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct EnumType<enum class AssetType>
{
    static const char* name();
    static const std::map<const char*, int> values();
};

