// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

#include "asset_type_generated.h"

ENUM()
enum class AssetType : int
{
    None = 0,
    Image,
    Prefab,
    Scene,
    SpriteAnimation,
    Text,
    Tileset
};