// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Type<struct AssetRecord> : reflect::RegisteredInTypeFactory<struct AssetRecord>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, AssetRecord& type);
    static std::string to_string(const AssetRecord& type);
    static void from_json(const std::string& json, AssetRecord& type);
    static std::string to_json(const AssetRecord& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};

template <>
struct reflect::Type<struct AssetDatabase> : reflect::RegisteredInTypeFactory<struct AssetDatabase>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, AssetDatabase& type);
    static std::string to_string(const AssetDatabase& type);
    static void from_json(const std::string& json, AssetDatabase& type);
    static std::string to_json(const AssetDatabase& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};

template <>
struct reflect::Type<struct AssetLoader> : reflect::RegisteredInTypeFactory<struct AssetLoader>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, AssetLoader& type);
    static std::string to_string(const AssetLoader& type);
    static void from_json(const std::string& json, AssetLoader& type);
    static std::string to_json(const AssetLoader& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};