// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "asset_handler.h"

const reflect::meta_t& reflect::Type<AssetHandler>::meta()
{
    static reflect::meta_t s_meta {
    };
    return s_meta;
}
const char* const reflect::Type<AssetHandler>::name() { return "AssetHandler"; }

const reflect::properties_t& Type<AssetHandler>::properties()
{
    static reflect::properties_t s_properties {
    };
    return s_properties;
}

std::size_t reflect::Type<AssetHandler>::size()
{
    return sizeof(AssetHandler);
}

void reflect::Type<AssetHandler>::from_string(const std::string& str, AssetHandler& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
}

std::string reflect::Type<AssetHandler>::to_string(const AssetHandler& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<AssetHandler>::from_json(const std::string& json, AssetHandler& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<AssetHandler>::to_json(const AssetHandler& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "AssetHandler" << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& AssetHandler::type_meta() const { return reflect::Type<AssetHandler>::meta(); }
const char* const AssetHandler::type_name() const { return reflect::Type<AssetHandler>::name(); }
const reflect::properties_t& AssetHandler::type_properties() const { return reflect::Type<AssetHandler>::properties(); }
AssetHandler::operator std::string() const { return reflect::Type<AssetHandler>::to_string(*this); }
void AssetHandler::from_string(const std::string& str) { reflect::Type<AssetHandler>::from_string(str, *this); }
void AssetHandler::from_json(const std::string& json) { reflect::Type<AssetHandler>::from_json(json, *this); }
std::string AssetHandler::to_json(const std::string& offset) const { return reflect::Type<AssetHandler>::to_json(*this, offset); }