// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Type<struct AudioAsset> : reflect::RegisteredInTypeFactory<struct AudioAsset>
{
    static IType* const instantiate();
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, AudioAsset& type);
    static std::string to_string(const AudioAsset& type);
    static void from_json(const std::string& json, AudioAsset& type);
    static std::string to_json(const AudioAsset& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};

template <>
struct reflect::Type<struct AudioAssetLoader> : reflect::RegisteredInTypeFactory<struct AudioAssetLoader>
{
    static IType* const instantiate();
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, AudioAssetLoader& type);
    static std::string to_string(const AudioAssetLoader& type);
    static void from_json(const std::string& json, AudioAssetLoader& type);
    static std::string to_json(const AudioAssetLoader& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};