// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "prefab_asset.h"
#pragma warning(disable: 4100)

const reflect::meta_t& reflect::Type<PrefabAsset>::meta()
{
    static reflect::meta_t s_meta {
        { "Type", "Asset" },
    };
    return s_meta;
}
const char* const reflect::Type<PrefabAsset>::name() { return "PrefabAsset"; }

const reflect::properties_t& Type<PrefabAsset>::properties()
{
    static reflect::properties_t s_properties {
        // Parent class Asset properties
        { "id", reflect::Property{ offsetof(PrefabAsset, id), reflect::meta_t { }, "id", reflect::PropertyType{ "uuid", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(uuid), reflect::PropertyType::Type::T_type } } },
        { "type", reflect::Property{ offsetof(PrefabAsset, type), reflect::meta_t { }, "type", reflect::PropertyType{ "int", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(int), reflect::PropertyType::Type::T_int } } },
        // Properties
    };
    return s_properties;
}

std::size_t reflect::Type<PrefabAsset>::size()
{
    return sizeof(PrefabAsset);
}

void reflect::Type<PrefabAsset>::from_string(const std::string& str, PrefabAsset& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    // Parent class Asset properties
    {
        std::string pack;
        stream >> pack;
        type.id.from_string(pack);
    }
    stream >> type.type;
    // Properties
}

std::string reflect::Type<PrefabAsset>::to_string(const PrefabAsset& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    // Parent class Asset properties
    stream << static_cast<std::string>(type.id);
    stream << type.type;
    // Properties
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<PrefabAsset>::from_json(const std::string& json, PrefabAsset& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            // Parent class Asset properties
            if (key == "id") type.id.from_json(value);
            if (key == "type") reflect::encoding::json::Deserializer::parse(value, type.type);
            // Properties
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<PrefabAsset>::to_json(const PrefabAsset& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"PrefabAsset\"" << "," << std::endl;
    // Parent class Asset properties
    stream << offset << "    " << "\"id\": " << type.id.to_json(offset + "    ") << "," << std::endl;
    stream << offset << "    " << "\"type\": " << reflect::encoding::json::Serializer::to_string(type.type) << "," << std::endl;
    // Properties
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& PrefabAsset::type_meta() const { return reflect::Type<PrefabAsset>::meta(); }
const char* const PrefabAsset::type_name() const { return reflect::Type<PrefabAsset>::name(); }
const reflect::properties_t& PrefabAsset::type_properties() const { return reflect::Type<PrefabAsset>::properties(); }
PrefabAsset::operator std::string() const { return reflect::Type<PrefabAsset>::to_string(*this); }
void PrefabAsset::from_string(const std::string& str)
{
    reflect::Type<PrefabAsset>::from_string(str, *this);
    type_initialize();
}
void PrefabAsset::from_json(const std::string& json)
{
    reflect::Type<PrefabAsset>::from_json(json, *this);
    type_initialize();
}
std::string PrefabAsset::to_json(const std::string& offset) const { return reflect::Type<PrefabAsset>::to_json(*this, offset); }

const reflect::meta_t& reflect::Type<PrefabAssetLoader>::meta()
{
    static reflect::meta_t s_meta {
        { "Type", "AssetLoader" },
    };
    return s_meta;
}
const char* const reflect::Type<PrefabAssetLoader>::name() { return "PrefabAssetLoader"; }

const reflect::properties_t& Type<PrefabAssetLoader>::properties()
{
    static reflect::properties_t s_properties {
        // Parent class AssetLoader properties
        // Properties
    };
    return s_properties;
}

std::size_t reflect::Type<PrefabAssetLoader>::size()
{
    return sizeof(PrefabAssetLoader);
}

void reflect::Type<PrefabAssetLoader>::from_string(const std::string& str, PrefabAssetLoader& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    // Parent class AssetLoader properties
    // Properties
}

std::string reflect::Type<PrefabAssetLoader>::to_string(const PrefabAssetLoader& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    // Parent class AssetLoader properties
    // Properties
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<PrefabAssetLoader>::from_json(const std::string& json, PrefabAssetLoader& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            // Parent class AssetLoader properties
            // Properties
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<PrefabAssetLoader>::to_json(const PrefabAssetLoader& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"PrefabAssetLoader\"" << "," << std::endl;
    // Parent class AssetLoader properties
    // Properties
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& PrefabAssetLoader::type_meta() const { return reflect::Type<PrefabAssetLoader>::meta(); }
const char* const PrefabAssetLoader::type_name() const { return reflect::Type<PrefabAssetLoader>::name(); }
const reflect::properties_t& PrefabAssetLoader::type_properties() const { return reflect::Type<PrefabAssetLoader>::properties(); }
PrefabAssetLoader::operator std::string() const { return reflect::Type<PrefabAssetLoader>::to_string(*this); }
void PrefabAssetLoader::from_string(const std::string& str)
{
    reflect::Type<PrefabAssetLoader>::from_string(str, *this);
    type_initialize();
}
void PrefabAssetLoader::from_json(const std::string& json)
{
    reflect::Type<PrefabAssetLoader>::from_json(json, *this);
    type_initialize();
}
std::string PrefabAssetLoader::to_json(const std::string& offset) const { return reflect::Type<PrefabAssetLoader>::to_json(*this, offset); }