// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "scene_asset.h"

const meta_t& SceneAsset::getTypeMeta() const { return __SceneAssetType::type().meta; }
const std::string& SceneAsset::getTypeName() const { return __SceneAssetType::type().name; }
const properties_t SceneAsset::getTypeProperties() const {
    properties_t properties = Asset::getTypeProperties();
    return properties;
}
std::size_t SceneAsset::getTypeSize() const { return __SceneAssetType::type().size; }

const TypeDefinition& __SceneAssetType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new SceneAsset(); }, "SceneAsset", {
    }, sizeof(SceneAsset));
    return s_typeDefinition;
}
