// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Type<struct SpriteAnimationAsset> : reflect::RegisteredInTypeFactory<struct SpriteAnimationAsset>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, SpriteAnimationAsset& type);
    static std::string to_string(const SpriteAnimationAsset& type);
    static void from_json(const std::string& json, SpriteAnimationAsset& type);
    static std::string to_json(const SpriteAnimationAsset& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};

template <>
struct reflect::Type<struct SpriteAnimationLoader> : reflect::RegisteredInTypeFactory<struct SpriteAnimationLoader>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, SpriteAnimationLoader& type);
    static std::string to_string(const SpriteAnimationLoader& type);
    static void from_json(const std::string& json, SpriteAnimationLoader& type);
    static std::string to_json(const SpriteAnimationLoader& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};