// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct __TilesetAssetType : RegisteredInTypeFactory<__TilesetAssetType>
{
    __TilesetAssetType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

