// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Type<struct UserInterfaceAsset> : reflect::RegisteredInTypeFactory<struct UserInterfaceAsset>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, UserInterfaceAsset& type);
    static std::string to_string(const UserInterfaceAsset& type);
    static void from_json(const std::string& json, UserInterfaceAsset& type);
    static std::string to_json(const UserInterfaceAsset& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};

template <>
struct reflect::Type<struct UserInterfaceAssetLoader> : reflect::RegisteredInTypeFactory<struct UserInterfaceAssetLoader>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, UserInterfaceAssetLoader& type);
    static std::string to_string(const UserInterfaceAssetLoader& type);
    static void from_json(const std::string& json, UserInterfaceAssetLoader& type);
    static std::string to_json(const UserInterfaceAssetLoader& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};