// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Type<struct WidgetAsset> : reflect::RegisteredInTypeFactory<struct WidgetAsset>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, WidgetAsset& type);
    static std::string to_string(const WidgetAsset& type);
    static void from_json(const std::string& json, WidgetAsset& type);
    static std::string to_json(const WidgetAsset& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};

template <>
struct reflect::Type<struct WidgetAssetLoader> : reflect::RegisteredInTypeFactory<struct WidgetAssetLoader>
{
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, WidgetAssetLoader& type);
    static std::string to_string(const WidgetAssetLoader& type);
    static void from_json(const std::string& json, WidgetAssetLoader& type);
    static std::string to_json(const WidgetAssetLoader& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};