// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtproto/runtime.h>

enum class CombatType : int
{
    Meele = 0,
    Ranged = 1,
};

template <>
struct EnumType<CombatType>
{
    static const char* name() { return "CombatType"; }
    static const std::map<const char*, int> values()
    {
        static std::map<const char*, int> s_values {
            { "Meele", static_cast<int>(CombatType::Meele) },
            { "Ranged", static_cast<int>(CombatType::Ranged) },
        };
        return s_values;
    }
};

