// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "engine_settings.h"

const char* const reflect::Enum<EngineMode>::name() { return "EngineMode"; }
const reflect::enum_values_t& reflect::Enum<EngineMode>::values()
{
    static reflect::enum_values_t s_values{
        { "Editor", static_cast<int>(EngineMode::Editor) }, 
        { "Server", static_cast<int>(EngineMode::Server) }, 
        { "Standalone", static_cast<int>(EngineMode::Standalone) }, 
    };
    return s_values;
}

const char* const reflect::Enum<FpsMode>::name() { return "FpsMode"; }
const reflect::enum_values_t& reflect::Enum<FpsMode>::values()
{
    static reflect::enum_values_t s_values{
        { "Fps30", static_cast<int>(FpsMode::Fps30) }, 
        { "Fps60", static_cast<int>(FpsMode::Fps60) }, 
        { "Fps90", static_cast<int>(FpsMode::Fps90) }, 
        { "Unlimited", static_cast<int>(FpsMode::Unlimited) }, 
    };
    return s_values;
}

const reflect::meta_t& reflect::Type<EngineSettings>::meta()
{
    static reflect::meta_t s_meta {
    };
    return s_meta;
}
const char* const reflect::Type<EngineSettings>::name() { return "EngineSettings"; }

const reflect::properties_t& Type<EngineSettings>::properties()
{
    static reflect::properties_t s_properties {
        { "fps", reflect::Property{ offsetof(EngineSettings, fps), reflect::meta_t { }, "fps", reflect::PropertyType{ "FpsMode", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(FpsMode), reflect::PropertyType::Type::T_enum } } },
        { "mode", reflect::Property{ offsetof(EngineSettings, mode), reflect::meta_t { }, "mode", reflect::PropertyType{ "EngineMode", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(EngineMode), reflect::PropertyType::Type::T_enum } } },
        { "workspacePath", reflect::Property{ offsetof(EngineSettings, workspacePath), reflect::meta_t { }, "workspacePath", reflect::PropertyType{ "std::filesystem::path", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(std::filesystem::path), reflect::PropertyType::Type::T_unknown } } },
    };
    return s_properties;
}

std::size_t reflect::Type<EngineSettings>::size()
{
    return sizeof(EngineSettings);
}

void reflect::Type<EngineSettings>::from_string(const std::string& str, EngineSettings& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    {
        int pack;
        stream >> pack;
        type.fps = static_cast<FpsMode>(type.fps);
    }
    {
        int pack;
        stream >> pack;
        type.mode = static_cast<EngineMode>(type.mode);
    }
}

std::string reflect::Type<EngineSettings>::to_string(const EngineSettings& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    stream << static_cast<int>(type.fps);
    stream << static_cast<int>(type.mode);
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<EngineSettings>::from_json(const std::string& json, EngineSettings& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            if (key == "fps")
            {
                std::string temp;
                reflect::encoding::json::Deserializer::parse(value, temp);
                stringToEnum(value, type.fps);
            }
            if (key == "mode")
            {
                std::string temp;
                reflect::encoding::json::Deserializer::parse(value, temp);
                stringToEnum(value, type.mode);
            }
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<EngineSettings>::to_json(const EngineSettings& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "EngineSettings" << "," << std::endl;
    stream << offset << "    " << "\"fps\": " << reflect::encoding::json::Serializer::to_string(enumToString(type.fps)) << "," << std::endl;
    stream << offset << "    " << "\"mode\": " << reflect::encoding::json::Serializer::to_string(enumToString(type.mode)) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& EngineSettings::type_meta() const { return reflect::Type<EngineSettings>::meta(); }
const char* const EngineSettings::type_name() const { return reflect::Type<EngineSettings>::name(); }
const reflect::properties_t& EngineSettings::type_properties() const { return reflect::Type<EngineSettings>::properties(); }
EngineSettings::operator std::string() const { return reflect::Type<EngineSettings>::to_string(*this); }
void EngineSettings::from_string(const std::string& str) { reflect::Type<EngineSettings>::from_string(str, *this); }
void EngineSettings::from_json(const std::string& json) { reflect::Type<EngineSettings>::from_json(json, *this); }
std::string EngineSettings::to_json(const std::string& offset) const { return reflect::Type<EngineSettings>::to_json(*this, offset); }