// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "audio.h"
#pragma warning(disable: 4100)

const char* const reflect::Enum<AudioType>::name() { return "AudioType"; }
const reflect::enum_values_t& reflect::Enum<AudioType>::values()
{
    static reflect::enum_values_t s_values{
        { "flac", static_cast<int>(AudioType::flac) }, 
        { "mp3", static_cast<int>(AudioType::mp3) }, 
        { "wav", static_cast<int>(AudioType::wav) }, 
    };
    return s_values;
}