// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "prefab.h"

const reflect::meta_t& reflect::Type<Prefab>::meta()
{
    static reflect::meta_t s_meta {
    };
    return s_meta;
}
const char* const reflect::Type<Prefab>::name() { return "Prefab"; }

const reflect::properties_t& Type<Prefab>::properties()
{
    static reflect::properties_t s_properties {
        { "entity", reflect::Property{ offsetof(Prefab, entity), reflect::meta_t { }, "entity", reflect::PropertyType{ "Entity", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(Entity), reflect::PropertyType::Type::T_type } } },
    };
    return s_properties;
}

std::size_t reflect::Type<Prefab>::size()
{
    return sizeof(Prefab);
}

void reflect::Type<Prefab>::from_string(const std::string& str, Prefab& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    {
        std::string pack;
        stream >> pack;
        type.entity.from_string(pack);
    }
}

std::string reflect::Type<Prefab>::to_string(const Prefab& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    stream << static_cast<std::string>(type.entity);
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<Prefab>::from_json(const std::string& json, Prefab& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            if (key == "entity") type.entity.from_json(value);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<Prefab>::to_json(const Prefab& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"Prefab\"" << "," << std::endl;
    stream << offset << "    " << "\"entity\": " << type.entity.to_json(offset + "    ") << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& Prefab::type_meta() const { return reflect::Type<Prefab>::meta(); }
const char* const Prefab::type_name() const { return reflect::Type<Prefab>::name(); }
const reflect::properties_t& Prefab::type_properties() const { return reflect::Type<Prefab>::properties(); }
Prefab::operator std::string() const { return reflect::Type<Prefab>::to_string(*this); }
void Prefab::from_string(const std::string& str)
{
    reflect::Type<Prefab>::from_string(str, *this);
    type_initialize();
}
void Prefab::from_json(const std::string& json)
{
    reflect::Type<Prefab>::from_json(json, *this);
    type_initialize();
}
std::string Prefab::to_json(const std::string& offset) const { return reflect::Type<Prefab>::to_json(*this, offset); }