// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct __SceneSettingsDataType : RegisteredInTypeFactory<__SceneSettingsDataType>
{
    __SceneSettingsDataType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

struct __SceneDataType : RegisteredInTypeFactory<__SceneDataType>
{
    __SceneDataType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

