// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct __SpriteAnimationFrameType : RegisteredInTypeFactory<__SpriteAnimationFrameType>
{
    __SpriteAnimationFrameType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

struct __SpriteAnimationDataType : RegisteredInTypeFactory<__SpriteAnimationDataType>
{
    __SpriteAnimationDataType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

