// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "sprite_animation.h"
#pragma warning(disable: 4100)

const reflect::meta_t& reflect::Type<SpriteAnimation>::meta()
{
    static reflect::meta_t s_meta {
    };
    return s_meta;
}
const char* const reflect::Type<SpriteAnimation>::name() { return "SpriteAnimation"; }

const reflect::properties_t& Type<SpriteAnimation>::properties()
{
    static reflect::properties_t s_properties {
        { "image", reflect::Property{ offsetof(SpriteAnimation, image), reflect::meta_t { }, "image", reflect::PropertyType{ "ImageAsset", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(ImageAsset), reflect::PropertyType::Type::T_type } } },
        { "startingFrame", reflect::Property{ offsetof(SpriteAnimation, startingFrame), reflect::meta_t { }, "startingFrame", reflect::PropertyType{ "int", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(int), reflect::PropertyType::Type::T_int } } },
        { "frames", reflect::Property{ offsetof(SpriteAnimation, frames), reflect::meta_t { }, "frames", reflect::PropertyType{ "std::vector<SpriteAnimationFrame>", { 
            reflect::PropertyType{ "SpriteAnimationFrame", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(SpriteAnimationFrame), reflect::PropertyType::Type::T_unknown },
        }, reflect::PropertyType::DecoratorType::D_raw, sizeof(std::vector<SpriteAnimationFrame>), reflect::PropertyType::Type::T_template } } },
    };
    return s_properties;
}

std::size_t reflect::Type<SpriteAnimation>::size()
{
    return sizeof(SpriteAnimation);
}

void reflect::Type<SpriteAnimation>::from_string(const std::string& str, SpriteAnimation& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    {
        std::string pack;
        stream >> pack;
        type.image.from_string(pack);
    }
    stream >> type.startingFrame;
}

std::string reflect::Type<SpriteAnimation>::to_string(const SpriteAnimation& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    stream << static_cast<std::string>(type.image);
    stream << type.startingFrame;
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<SpriteAnimation>::from_json(const std::string& json, SpriteAnimation& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            if (key == "image") type.image.from_json(value);
            if (key == "startingFrame") reflect::encoding::json::Deserializer::parse(value, type.startingFrame);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<SpriteAnimation>::to_json(const SpriteAnimation& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"SpriteAnimation\"" << "," << std::endl;
    stream << offset << "    " << "\"image\": " << type.image.to_json(offset + "    ") << "," << std::endl;
    stream << offset << "    " << "\"startingFrame\": " << reflect::encoding::json::Serializer::to_string(type.startingFrame) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& SpriteAnimation::type_meta() const { return reflect::Type<SpriteAnimation>::meta(); }
const char* const SpriteAnimation::type_name() const { return reflect::Type<SpriteAnimation>::name(); }
const reflect::properties_t& SpriteAnimation::type_properties() const { return reflect::Type<SpriteAnimation>::properties(); }
SpriteAnimation::operator std::string() const { return reflect::Type<SpriteAnimation>::to_string(*this); }
void SpriteAnimation::from_string(const std::string& str)
{
    reflect::Type<SpriteAnimation>::from_string(str, *this);
    type_initialize();
}
void SpriteAnimation::from_json(const std::string& json)
{
    reflect::Type<SpriteAnimation>::from_json(json, *this);
    type_initialize();
}
std::string SpriteAnimation::to_json(const std::string& offset) const { return reflect::Type<SpriteAnimation>::to_json(*this, offset); }