// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Type<struct SpriteAnimationFrame> : reflect::RegisteredInTypeFactory<struct SpriteAnimationFrame>
{
    static IType* const instantiate();
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, SpriteAnimationFrame& type);
    static std::string to_string(const SpriteAnimationFrame& type);
    static void from_json(const std::string& json, SpriteAnimationFrame& type);
    static std::string to_json(const SpriteAnimationFrame& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};

template <>
struct reflect::Type<struct SpriteAnimation> : reflect::RegisteredInTypeFactory<struct SpriteAnimation>
{
    static IType* const instantiate();
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, SpriteAnimation& type);
    static std::string to_string(const SpriteAnimation& type);
    static void from_json(const std::string& json, SpriteAnimation& type);
    static std::string to_json(const SpriteAnimation& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};