// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SpriteAnimationFrameType : RegisteredInTypeFactory<SpriteAnimationFrameType>
{
    SpriteAnimationFrameType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

struct SpriteAnimationDataType : RegisteredInTypeFactory<SpriteAnimationDataType>
{
    SpriteAnimationDataType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

