// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct __TileDataType : RegisteredInTypeFactory<__TileDataType>
{
    __TileDataType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

struct __TilesetDataType : RegisteredInTypeFactory<__TilesetDataType>
{
    __TilesetDataType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

