// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct __TileType : RegisteredInTypeFactory<__TileType>
{
    __TileType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

struct __TilesetType : RegisteredInTypeFactory<__TilesetType>
{
    __TilesetType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

