// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "user_interface.h"
#pragma warning(disable: 4100)

const reflect::meta_t& reflect::Type<UserInterface>::meta()
{
    static reflect::meta_t s_meta {
    };
    return s_meta;
}
const char* const reflect::Type<UserInterface>::name() { return "UserInterface"; }

const reflect::properties_t& Type<UserInterface>::properties()
{
    static reflect::properties_t s_properties {
        { "controls", reflect::Property{ offsetof(UserInterface, controls), reflect::meta_t { }, "controls", reflect::PropertyType{ "std::vector<std::unique_ptr<Control>>", { 
            reflect::PropertyType{ "std::unique_ptr<Control>", { 
                reflect::PropertyType{ "Control", {  }, reflect::PropertyType::DecoratorType::D_raw, sizeof(Control), reflect::PropertyType::Type::T_type },
            }, reflect::PropertyType::DecoratorType::D_raw, sizeof(std::unique_ptr<Control>), reflect::PropertyType::Type::T_template },
        }, reflect::PropertyType::DecoratorType::D_raw, sizeof(std::vector<std::unique_ptr<Control>>), reflect::PropertyType::Type::T_template } } },
    };
    return s_properties;
}

std::size_t reflect::Type<UserInterface>::size()
{
    return sizeof(UserInterface);
}

void reflect::Type<UserInterface>::from_string(const std::string& str, UserInterface& type)
{
    reflect::encoding::ByteBuffer buffer;
    std::transform(
        std::begin(str),
        std::end(str),
        std::back_inserter(buffer),
        [](const char c)
        {
            return std::byte(c);
        }
    );
    
    reflect::encoding::InputByteStream stream(buffer);
    std::string _name;
    stream >> _name;
    if (_name != name()) return;
    
    {
        type.controls.clear();
        std::size_t size;
        stream >> size;
        for (int i = 0; i < size; ++i)
        {
            std::unique_ptr<Control> element;
            {
                bool valid = false;
                stream >> valid;
                if (valid)
                {
                    reflect::encoding::InputByteStream temp_stream(buffer, stream.getIndex());
                    std::size_t temp_element_size;
                    temp_stream >> temp_element_size;
                    std::string type_id;
                    temp_stream >> type_id;
                    if (type_id == Type<Control>::name())
                    {
                        element = std::make_unique<Control>();
                    }
                    else
                    {
                        element = std::unique_ptr<Control>(TypeFactory::instantiate<Control>(type_id));
                    }
                    {
                        std::string pack;
                        stream >> pack;
                        element->from_string(pack);
                    }
                }
            }
            type.controls.push_back(std::move(element));
        }
    }
}

std::string reflect::Type<UserInterface>::to_string(const UserInterface& type)
{
    reflect::encoding::ByteBuffer buffer;
    reflect::encoding::OutputByteStream stream(buffer);
    stream << name();
    
    {
        stream << type.controls.size();
        for (const auto& element : type.controls)
        {
            stream << (element ? true : false); 
            if(element) stream << static_cast<std::string>(*element);
        }
    }
    
    return std::string(reinterpret_cast<const char*>(&stream.getBuffer()[0]), stream.getBuffer().size());
}

void reflect::Type<UserInterface>::from_json(const std::string& json, UserInterface& type)
{
    std::string src{ reflect::encoding::json::Deserializer::trim(json, reflect::encoding::json::Deserializer::space) };
    
    size_t index = 0;
    std::string key;
    while ((index = reflect::encoding::json::Deserializer::next_key(src, key)) != std::string::npos)
    {
        src = src.substr(index + 2);
        src = reflect::encoding::json::Deserializer::ltrim(src, reflect::encoding::json::Deserializer::space);
        std::string value;
        index = reflect::encoding::json::Deserializer::next_value(src, value);
        if (index != std::string::npos)
        {
            if (key == "controls") reflect::encoding::json::Deserializer::parse(value, type.controls);
            src = src.substr(index + 1);
        }
        else break;
    };
}

std::string reflect::Type<UserInterface>::to_json(const UserInterface& type, const std::string& offset)
{
    std::stringstream stream;
    stream << "{" << std::endl;
    stream << offset << "    " << "\"type_id\": " << "\"UserInterface\"" << "," << std::endl;
    stream << offset << "    " << "\"controls\": " << reflect::encoding::json::Serializer::to_string(type.controls) << "," << std::endl;
    stream << offset << "}";
    return stream.str();
}

const reflect::meta_t& UserInterface::type_meta() const { return reflect::Type<UserInterface>::meta(); }
const char* const UserInterface::type_name() const { return reflect::Type<UserInterface>::name(); }
const reflect::properties_t& UserInterface::type_properties() const { return reflect::Type<UserInterface>::properties(); }
UserInterface::operator std::string() const { return reflect::Type<UserInterface>::to_string(*this); }
void UserInterface::from_string(const std::string& str)
{
    reflect::Type<UserInterface>::from_string(str, *this);
    type_initialize();
}
void UserInterface::from_json(const std::string& json)
{
    reflect::Type<UserInterface>::from_json(json, *this);
    type_initialize();
}
std::string UserInterface::to_json(const std::string& offset) const { return reflect::Type<UserInterface>::to_json(*this, offset); }