// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct reflect::Type<struct Widget> : reflect::RegisteredInTypeFactory<struct Widget>
{
    static IType* const instantiate();
    static const reflect::meta_t& meta();
    static const char* const name();
    static const reflect::properties_t& properties();
    static std::size_t size();

    static void from_string(const std::string& str, Widget& type);
    static std::string to_string(const Widget& type);
    static void from_json(const std::string& json, Widget& type);
    static std::string to_json(const Widget& type, const std::string& offset = "");

    static bool registered() { return type_registered; };
};