// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "game_mode.h"

const meta_t& GameMode::getTypeMeta() const { return GameModeType::type().meta; }
const std::string& GameMode::getTypeName() const { return GameModeType::type().name; }
const properties_t GameMode::getTypeProperties() const {
    properties_t properties;
    return properties;
}
std::size_t GameMode::getTypeSize() const { return GameModeType::type().size; }

const TypeDefinition& GameModeType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new GameMode(); }, "GameMode", {
        std::make_pair("Category", "GameMode"),
    }, sizeof(GameMode));
    return s_typeDefinition;
}
