// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct __WeaponLevelType : RegisteredInTypeFactory<__WeaponLevelType>
{
    __WeaponLevelType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

struct __WeaponItemType : RegisteredInTypeFactory<__WeaponItemType>
{
    __WeaponItemType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

struct __GameSettingsType : RegisteredInTypeFactory<__GameSettingsType>
{
    __GameSettingsType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

