// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct WeaponLevelType : RegisteredInTypeFactory<WeaponLevelType>
{
    WeaponLevelType() = delete;

    static const Type& type();
    static bool registered() { return value; };
};

struct WeaponItemType : RegisteredInTypeFactory<WeaponItemType>
{
    WeaponItemType() = delete;

    static const Type& type();
    static bool registered() { return value; };
};

struct GameSettingsType : RegisteredInTypeFactory<GameSettingsType>
{
    GameSettingsType() = delete;

    static const Type& type();
    static bool registered() { return value; };
};

