// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct WaveType : RegisteredInTypeFactory<WaveType>
{
    WaveType() = delete;

    static const Type& type();
    static bool registered() { return value; };
};

