// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct Body2dComponentType : RegisteredInTypeFactory<Body2dComponentType>
{
    Body2dComponentType() = delete;

    static const Type& type();
    static bool registered() { return value; };
};

