// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct Body2dComponentType : RegisteredInTypeFactory<Body2dComponentType>
{
    Body2dComponentType();

    static const meta_t& meta();
    static const char* name();
    static class Body2dComponent* const instantiate();
    static bool registered() { return value; };
};

