// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "body2d_component.h"

const meta_t& Body2dComponent::getTypeMeta() const { return __Body2dComponentType::type().meta; }
const std::string& Body2dComponent::getTypeName() const { return __Body2dComponentType::type().name; }
const properties_t Body2dComponent::getTypeProperties() const {
    properties_t properties = Component::getTypeProperties();
    return properties;
}
std::size_t Body2dComponent::getTypeSize() const { return __Body2dComponentType::type().size; }
const meta_t& Body2dComponent::staticTypeMeta() { return __Body2dComponentType::type().meta; }
const std::string& Body2dComponent::staticTypeName() { return __Body2dComponentType::type().name; }

const TypeDefinition& __Body2dComponentType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new Body2dComponent(); }, "Body2dComponent", {
        std::make_pair("Type", "Component"),
    }, sizeof(Body2dComponent));
    return s_typeDefinition;
}
