// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "body2d_component.h"

const meta_t& Body2dComponent::getTypeMeta() const { return Body2dComponentType::meta(); }
const char* Body2dComponent::getTypeName() const { return Body2dComponentType::name(); }
const properties_t Body2dComponent::getTypeProperties() const {
    member_address_t origin = reinterpret_cast<member_address_t>(this);
    properties_t properties = Component::getTypeProperties();
    return properties;
}
std::size_t Body2dComponent::getTypeSize() const { return sizeof(Body2dComponent); }

Body2dComponentType::Body2dComponentType()
{
    TypeFactoryRegister::load(Body2dComponentType::name(), []() -> const meta_t& { return Body2dComponentType::meta(); }, []() -> IType* { return Body2dComponentType::instantiate(); });
}

Body2dComponent* const Body2dComponentType::instantiate()
{
    return new Body2dComponent();
}

const meta_t& Body2dComponentType::meta()
{
    static meta_t s_meta{
    };
    return s_meta;
}

const char* Body2dComponentType::name() { return "Body2dComponent"; }

Body2dComponentType __body2dcomponent_type;

