// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "camera_controller_2d_component.h"

const meta_t& CameraController2dComponent::getTypeMeta() const { return CameraController2dComponentType::meta(); }
const char* CameraController2dComponent::getTypeName() const { return CameraController2dComponentType::name(); }
const properties_t CameraController2dComponent::getTypeProperties() const {
    member_address_t origin = reinterpret_cast<member_address_t>(this);
    properties_t properties = Component::getTypeProperties();
    properties.insert(std::make_pair<std::string, Property>("speed", Property("speed", NativeType::NT_int, "int", sizeof(int), origin + offsetof(CameraController2dComponent, speed), {
    })));
    properties.insert(std::make_pair<std::string, Property>("zoomSpeed", Property("zoomSpeed", NativeType::NT_int, "int", sizeof(int), origin + offsetof(CameraController2dComponent, zoomSpeed), {
    })));
    return properties;
}
std::size_t CameraController2dComponent::getTypeSize() const { return sizeof(CameraController2dComponent); }

CameraController2dComponentType::CameraController2dComponentType()
{
    TypeFactoryRegister::load(CameraController2dComponentType::name(), []() -> const meta_t& { return CameraController2dComponentType::meta(); }, []() -> IType* { return CameraController2dComponentType::instantiate(); });
}

CameraController2dComponent* const CameraController2dComponentType::instantiate()
{
    return new CameraController2dComponent();
}

const meta_t& CameraController2dComponentType::meta()
{
    static meta_t s_meta{
    };
    return s_meta;
}

const char* CameraController2dComponentType::name() { return "CameraController2dComponent"; }

CameraController2dComponentType __cameracontroller2dcomponent_type;

