// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct CameraController2dComponentType : RegisteredInTypeFactory<CameraController2dComponentType>
{
    CameraController2dComponentType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

