// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct CameraController2dComponentType : RegisteredInTypeFactory<CameraController2dComponentType>
{
    CameraController2dComponentType();

    static const meta_t& meta();
    static const char* name();
    static class CameraController2dComponent* const instantiate();
    static bool registered() { return value; };
};

