// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct __CameraController2dComponentType : RegisteredInTypeFactory<__CameraController2dComponentType>
{
    __CameraController2dComponentType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

