// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct CameraController2dType
{
    CameraController2dType();

    static const meta_t& meta();
    static const char* name();
    static class CameraController2d* const instantiate();
};
extern CameraController2dType __cameracontroller2d_type;

