// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct CameraComponentType : RegisteredInTypeFactory<CameraComponentType>
{
    CameraComponentType();

    static const meta_t& meta();
    static const char* name();
    static class CameraComponent* const instantiate();
    static bool registered() { return value; };
};

