// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct Collider2dType
{
    Collider2dType();

    static const meta_t& meta();
    static const char* name();
    static class Collider2d* const instantiate();
};
extern Collider2dType __collider2d_type;

