// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct Collider2dComponentType : RegisteredInTypeFactory<Collider2dComponentType>
{
    Collider2dComponentType();

    static const meta_t& meta();
    static const char* name();
    static class Collider2dComponent* const instantiate();
    static bool registered() { return value; };
};

