// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct Collider2dComponentType : RegisteredInTypeFactory<Collider2dComponentType>
{
    Collider2dComponentType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

