// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct GizmosRendererType
{
    GizmosRendererType();

    static const meta_t& meta();
    static const char* name();
    static class GizmosRenderer* const instantiate();
};
extern GizmosRendererType __gizmosrenderer_type;

