// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct GizmosRendererComponentType : RegisteredInTypeFactory<GizmosRendererComponentType>
{
    GizmosRendererComponentType();

    static const meta_t& meta();
    static const char* name();
    static class GizmosRendererComponent* const instantiate();
    static bool registered() { return value; };
};

