// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct OrthographicCameraComponentType
{
    OrthographicCameraComponentType();

    static const meta_t& meta();
    static const char* name();
    static class OrthographicCameraComponent* const instantiate();
};
extern OrthographicCameraComponentType __orthographiccameracomponent_type;

