// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct OrthographicCameraType
{
    OrthographicCameraType();

    static const meta_t& meta();
    static const char* name();
    static class OrthographicCamera* const instantiate();
};
extern OrthographicCameraType __orthographiccamera_type;

