// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "orthographic_camera_component.h"

const meta_t& OrthographicCameraComponent::getTypeMeta() const { return OrthographicCameraComponentType::type().meta; }
const std::string& OrthographicCameraComponent::getTypeName() const { return OrthographicCameraComponentType::type().name; }
const properties_t OrthographicCameraComponent::getTypeProperties() const {
    member_address_t origin = reinterpret_cast<member_address_t>(this);
    properties_t properties = CameraComponent::getTypeProperties();
    properties.insert(std::make_pair<std::string, Property>("nearPlane", Property("nearPlane", NativeType::NT_int, "int", sizeof(int), origin + offsetof(OrthographicCameraComponent, nearPlane), {
    })));
    properties.insert(std::make_pair<std::string, Property>("farPlane", Property("farPlane", NativeType::NT_int, "int", sizeof(int), origin + offsetof(OrthographicCameraComponent, farPlane), {
    })));
    properties.insert(std::make_pair<std::string, Property>("pixelPerfect", Property("pixelPerfect", NativeType::NT_int, "int", sizeof(int), origin + offsetof(OrthographicCameraComponent, pixelPerfect), {
    })));
    properties.insert(std::make_pair<std::string, Property>("pixelsPerUnit", Property("pixelsPerUnit", NativeType::NT_int, "int", sizeof(int), origin + offsetof(OrthographicCameraComponent, pixelsPerUnit), {
    })));
    return properties;
}
std::size_t OrthographicCameraComponent::getTypeSize() const { return OrthographicCameraComponentType::type().size; }

const Type& OrthographicCameraComponentType::type()
{
    static const Type s_type([]() -> IType* { return new OrthographicCameraComponent(); }, "OrthographicCameraComponent", {
    }, sizeof(OrthographicCameraComponent));
    return s_type;
}
