// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct Particles2dComponentType : RegisteredInTypeFactory<Particles2dComponentType>
{
    Particles2dComponentType();

    static const meta_t& meta();
    static const char* name();
    static class Particles2dComponent* const instantiate();
    static bool registered() { return value; };
};

