// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct Particles2dType
{
    Particles2dType();

    static const meta_t& meta();
    static const char* name();
    static class Particles2d* const instantiate();
};
extern Particles2dType __particles2d_type;

