// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

#include "shape_type_generated.h"

ENUM()
enum class ShapeType : int
{
    Circle = 0,
    Rect = 1,
};
