// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "sprite_animator_component.h"

const meta_t& SpriteAnimatorComponent::getTypeMeta() const { return SpriteAnimatorComponentType::type().meta; }
const std::string& SpriteAnimatorComponent::getTypeName() const { return SpriteAnimatorComponentType::type().name; }
const properties_t SpriteAnimatorComponent::getTypeProperties() const {
    properties_t properties = Component::getTypeProperties();
    return properties;
}
std::size_t SpriteAnimatorComponent::getTypeSize() const { return SpriteAnimatorComponentType::type().size; }

const Type& SpriteAnimatorComponentType::type()
{
    static const Type s_type([]() -> IType* { return new SpriteAnimatorComponent(); }, "SpriteAnimatorComponent", {
    }, sizeof(SpriteAnimatorComponent));
    return s_type;
}
