// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SpriteAnimatorComponentType
{
    SpriteAnimatorComponentType();

    static const meta_t& meta();
    static const char* name();
    static class SpriteAnimatorComponent* const instantiate();
};
extern SpriteAnimatorComponentType __spriteanimatorcomponent_type;

