// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SpriteRendererType
{
    SpriteRendererType();

    static const meta_t& meta();
    static const char* name();
    static class SpriteRenderer* const instantiate();
};
extern SpriteRendererType __spriterenderer_type;

