// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#include "sprite_renderer_component.h"

const meta_t& SpriteRendererComponent::getTypeMeta() const { return SpriteRendererComponentType::type().meta; }
const std::string& SpriteRendererComponent::getTypeName() const { return SpriteRendererComponentType::type().name; }
const properties_t SpriteRendererComponent::getTypeProperties() const {
    member_address_t origin = reinterpret_cast<member_address_t>(this);
    properties_t properties = Component::getTypeProperties();
    properties.insert(std::make_pair<std::string, Property>("sprite", Property("sprite", Property::TypeDescriptor("SpriteAssetPtr", Property::Type::T_unknown, Property::DecoratorType::D_normalized, {}), sizeof(SpriteAssetPtr), origin + offsetof(SpriteRendererComponent, sprite), {
    })));
    properties.insert(std::make_pair<std::string, Property>("color", Property("color", Property::TypeDescriptor("graphics::Color", Property::Type::T_unknown, Property::DecoratorType::D_normalized, {}), sizeof(graphics::Color), origin + offsetof(SpriteRendererComponent, color), {
    })));
    properties.insert(std::make_pair<std::string, Property>("flipX", Property("flipX", Property::TypeDescriptor("bool", Property::Type::T_bool, Property::DecoratorType::D_normalized, {}), sizeof(bool), origin + offsetof(SpriteRendererComponent, flipX), {
    })));
    properties.insert(std::make_pair<std::string, Property>("flipY", Property("flipY", Property::TypeDescriptor("bool", Property::Type::T_bool, Property::DecoratorType::D_normalized, {}), sizeof(bool), origin + offsetof(SpriteRendererComponent, flipY), {
    })));
    return properties;
}
std::size_t SpriteRendererComponent::getTypeSize() const { return SpriteRendererComponentType::type().size; }

const TypeDefinition& SpriteRendererComponentType::type()
{
    static const TypeDefinition s_typeDefinition([]() -> Type* { return new SpriteRendererComponent(); }, "SpriteRendererComponent", {
        std::make_pair("Type", "Component"),
    }, sizeof(SpriteRendererComponent));
    return s_typeDefinition;
}
