// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

struct SpriteAnimatorType
{
    SpriteAnimatorType();

    static const meta_t& meta();
    static const char* name();
    static class SpriteAnimator* const instantiate();
};
extern SpriteAnimatorType __spriteanimator_type;

